include("cnncheckin_core.jl")
using .CNNCheckinCore

# Função para exibir ajuda
function show_help()
    println("🎯 Sistema de Reconhecimento Facial CNN Check-in v2.1")
    println()
    println("Uso:")
    println("  julia cnncheckin_train.jl                             # Treinar o modelo")
    println("  julia cnncheckin_identify.jl <imagem>                 # Identificar pessoa")
    println("  julia cnncheckin_info.jl                              # Informações do modelo")
    println("  julia cnncheckin_model_data.jl                        # Dados técnicos do modelo")
    println("  julia cnncheckin_validate.jl                          # Validar modelo/config/dados")
    println("  julia cnncheckin_export_config.jl [arquivo]           # Exportar configuração")
    println("  julia cnncheckin_help.jl                              # Mostrar esta ajuda")
    println()
    println("Exemplos:")
    println("  julia cnncheckin_train.jl")
    println("  julia cnncheckin_identify.jl ../dados/teste.jpg")
    println("  julia cnncheckin_info.jl")
    println("  julia cnncheckin_model_data.jl")
    println("  julia cnncheckin_export_config.jl backup_config_2025.toml")
    println()
    println("Estrutura de diretórios esperada:")
    println("  $(CNNCheckinCore.DATA_PATH)/")
    println("    ├── pessoa1-001.jpg")
    println("    ├── pessoa1-002.jpg")
    println("    ├── pessoa2-001.jpg")
    println("    └── ...")
    println()
    println("Formatos suportados: .jpg, .jpeg, .png, .bmp, .tiff")
    println()
    println("🔧 Configurações atuais:")
    println("  - Tamanho da imagem: $(CNNCheckinCore.IMG_SIZE)")
    println("  - Batch size: $(CNNCheckinCore.BATCH_SIZE)")
    println("  - Epochs máximos: $(CNNCheckinCore.EPOCHS)")
    println("  - Learning rate: $(CNNCheckinCore.LEARNING_RATE)")
    println()
    println("📄 Arquivos gerados:")
    println("  - $(CNNCheckinCore.MODEL_PATH)              # Pesos neurais (JLD2)")
    println("  - $(CNNCheckinCore.CONFIG_PATH)             # Configurações (TOML)")
    println("  - $(CNNCheckinCore.MODEL_DATA_TOML_PATH)    # Dados do modelo (TOML)")
    println()
    println("💡 Novidades v2.1:")
    println("  - Dados do modelo salvos em TOML editável")
    println("  - Comando model_data para detalhes técnicos")
    println("  - Histórico de predições salvo automaticamente")
    println("  - Estatísticas detalhadas dos pesos e camadas")
    println("  - Validação expandida incluindo dados TOML")
    println("  - Mapeamento pessoa → ID em formato legível")
    println()
    println("📊 O que contém o arquivo TOML de dados do modelo:")
    println("  - [model_summary]: arquitetura, dimensões, tipos")
    println("  - [layer_info]: detalhes de cada camada (Conv, Dense, etc.)")
    println("  - [weights_summary]: estatísticas dos pesos, tamanho do modelo")
    println("  - [person_mappings]: nome da pessoa → ID numérico")
    println("  - [prediction_examples]: histórico das últimas 50 predições")
    println("  - [metadata]: timestamps, versões, arquivos relacionados")
end

# Executar comando se for chamado diretamente
if abspath(PROGRAM_FILE) == @__FILE__
    show_help()
end