prediction_examples = []

[[layer_info]]
trainable = true
output_channels = 64
layer_number = 1
kernel_size = [3, 3]
input_channels = 3
layer_type = "Conv{2, 4, typeof(relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 2
num_features = 64
layer_type = "BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 3
layer_type = "Dropout{Float64, Colon, TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 4
pool_size = [2, 2]
layer_type = "MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 128
layer_number = 5
kernel_size = [3, 3]
input_channels = 64
layer_type = "Conv{2, 4, typeof(relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 6
num_features = 128
layer_type = "BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 7
layer_type = "Dropout{Float64, Colon, TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 8
pool_size = [2, 2]
layer_type = "MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 256
layer_number = 9
kernel_size = [3, 3]
input_channels = 128
layer_type = "Conv{2, 4, typeof(relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 10
num_features = 256
layer_type = "BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 11
layer_type = "Dropout{Float64, Colon, TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 12
pool_size = [2, 2]
layer_type = "MaxPool{2, 4}"
[[layer_info]]
trainable = true
output_channels = 256
layer_number = 13
kernel_size = [3, 3]
input_channels = 256
layer_type = "Conv{2, 4, typeof(relu), Array{Float32, 4}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 14
num_features = 256
layer_type = "BatchNorm{typeof(identity), Vector{Float32}, Float32, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 15
layer_type = "Dropout{Float64, Colon, TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 16
pool_size = [2, 2]
layer_type = "MaxPool{2, 4}"
[[layer_info]]
trainable = true
layer_number = 17
layer_type = "typeof(Flux.flatten)"
[[layer_info]]
trainable = true
layer_number = 18
input_size = 16384
output_size = 512
layer_type = "Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 19
layer_type = "Dropout{Float64, Colon, TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 20
input_size = 512
output_size = 256
layer_type = "Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}"
[[layer_info]]
trainable = true
layer_number = 21
layer_type = "Dropout{Float64, Colon, TaskLocalRNG}"
[[layer_info]]
trainable = true
layer_number = 22
input_size = 256
output_size = 1
layer_type = "Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}"

[person_mappings]
junior = 1

[model_summary]
input_shape = [128, 128]
created_at = "2025-09-02T23:58:21.260"
total_layers = 22
model_type = "CNN_FaceRecognition"
output_classes = 1

[metadata]
format_version = "1.0"
created_by = "cnncheckin.jl v1.0"
saved_at = "2025-09-02T23:58:21.993"
description = "CNN model for face recognition"

[weights_summary]
model_size_mb = 36.16
total_parameters = 9480128

    [weights_summary.layer_statistics.layer_20_weights]
    shape = [256, 512]
    max = 0.08838760107755661
    min = -0.08838816732168198
    count = 131072
    mean = 0.0001560057862661779
    std = 0.05105903372168541

    [weights_summary.layer_statistics.layer_22_weights]
    shape = [1, 256]
    max = 0.15228532254695892
    min = -0.15222673118114471
    count = 256
    mean = -0.0014249273808673024
    std = 0.08802322298288345

    [weights_summary.layer_statistics.layer_5_weights]
    shape = [3, 3, 64, 128]
    max = 0.05892444774508476
    min = -0.05892520025372505
    count = 73728
    mean = 0.00015288317808881402
    std = 0.034029003232717514

    [weights_summary.layer_statistics.layer_1_weights]
    shape = [3, 3, 3, 64]
    max = 0.09971791505813599
    min = -0.09946288168430328
    count = 1728
    mean = 0.0006421881262212992
    std = 0.05741146206855774

    [weights_summary.layer_statistics.layer_13_weights]
    shape = [3, 3, 256, 256]
    max = 0.036084290593862534
    min = -0.03608433157205582
    count = 589824
    mean = 4.821013499167748e-5
    std = 0.020844148471951485

    [weights_summary.layer_statistics.layer_18_weights]
    shape = [512, 16384]
    max = 0.01884445548057556
    min = -0.018844448029994965
    count = 8388608
    mean = -3.1907798074826133e-6
    std = 0.01088040042668581

    [weights_summary.layer_statistics.layer_9_weights]
    shape = [3, 3, 128, 256]
    max = 0.04166661202907562
    min = -0.041666217148303986
    count = 294912
    mean = -6.609907359234057e-6
    std = 0.02404274232685566
