[dados]
    [[dados.arquivo]]
        arquivo_nomeorigem = "2 Pessoas - 02_2026 - v.1.60.1.csv"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "2 Pessoas - 02_2026 - v.1.60.1 - Parte "
		
# 119467   2 Pessoas - 02_2026 - v.1.60.1 - Parte 1
# 238934   2 Pessoas - 02_2026 - v.1.60.1 - Parte 2
# 358401   2 Pessoas - 02_2026 - v.1.60.1 - Parte 3
# 477868   2 Pessoas - 02_2026 - v.1.60.1 - Parte 4