[dados]
    [[dados.arquivo]]
        arquivo_nomeorigem = "2 Pessoas - 02_2025 - v.1.47.csv"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "2 Pessoas - 02_2025 - v.1.47 - Parte "
		
# 107459   2 Pessoas - 12_2024 - v.1.45.1 Parte 1