[dados]
    [[dados.arquivo]]
        arquivo_nomeorigem = "matriz.jl"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "matriz - Parte "

# 121821   2 Pessoas - 06_2026 - v.1.64.3 - Parte 1
# 243642   2 Pessoas - 06_2026 - v.1.64.3 - Parte 2
# 365463   2 Pessoas - 06_2026 - v.1.64.3 - Parte 3
# 487284   2 Pessoas - 06_2026 - v.1.64.3 - Parte 4
