[dados]
    [[dados.arquivo]]
        arquivo_nomeorigem = "2 Pessoas - 02_2025 - v.1.47.2.csv"
        arquivo_qtde_parte = 4
        arquivo_nome_parte = "2 Pessoas - 02_2025 - v.1.47.2 - Parte "
		
# 110877   2 Pessoas - 02_2025 - v.1.47.2 - Parte 1
# 221754   2 Pessoas - 02_2025 - v.1.47.2 - Parte 2
# 332631   2 Pessoas - 02_2025 - v.1.47.2 - Parte 3
# 443508   2 Pessoas - 02_2025 - v.1.47.2 - Parte 4