CREATE TABLE ACAO_JUDICIAL (
    ADVOGADO_PREV VARCHAR(30) NULL,
    AUTOR VARCHAR(40) NULL,
    AUTUADO DATE NULL,
    COD_ACAO SMALLINT NULL,
    COD_LOCAL SMALLINT NULL,
    DATA_CADASTRO DATE NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    OFICIAL VARCHAR(30) NULL,
    REU VARCHAR(40) NULL,
    USUARIO VARCHAR(15) NULL,
    VARA VARCHAR(30) NULL
);

CREATE TABLE AGENCIA (
    COD_AGENCIA VARCHAR(5) NOT NULL,
    COD_BANCO VARCHAR(3) NOT NULL,
    DESC_AGENCIA VARCHAR(30) NOT NULL
);

CREATE TABLE AGENDA_MEDICA (
    COD_CREDENCIADO VARCHAR(8) NOT NULL,
    COD_TIPO_LOCAL SMALLINT NOT NULL,
    CONSULTA_RETORNO SMALLINT NULL,
    DATA_CADASTRO DATE NULL,
    DATA_CONSULTA DATE NOT NULL,
    HORA TIME(3) NULL,
    LANCADO CHARACTER(1) NULL,
    NUM_PLANILHA INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    NUM_SEQ_DEPENDE SMALLINT NOT NULL,
    RETORNO INTEGER NULL,
    SEQUENCIA SMALLINT NOT NULL,
    STATUS_CONSULTA CHARACTER(1) NOT NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE AMB (
    ACEITA_EXAME SMALLINT NOT NULL,
    ACEITA_PROCED_CIR SMALLINT NOT NULL,
    ACEITA_SERV_AUX SMALLINT NOT NULL,
    AUTORIZ_PREVIA SMALLINT NULL,
    CH_OPERACIONAL SMALLINT NULL,
    COD_AMB CHARACTER(8) NOT NULL,
    COEF_HONORARIO INTEGER NOT NULL,
    DATA_CADASTRO DATE NULL,
    DESC_AMB VARCHAR(50) NOT NULL,
    FILME DECIMAL(9, 4) NULL,
    NUM_AUXILIAR SMALLINT NULL,
    OBS VARCHAR(100) NULL,
    PERC_ACRESCIMO SMALLINT NULL,
    PERC_AUTOGERADO SMALLINT NOT NULL,
    PERC_DESCONTO SMALLINT NULL,
    PERC_OPERACIONAL SMALLINT NULL,
    PORTE_ANESTESICO SMALLINT NULL,
    REPETIR_DIAS SMALLINT NULL,
    TIPO_PROCEDIMENTO SMALLINT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_ACRESCIMO DECIMAL(9, 2) NULL,
    VALOR_DESCONTO DECIMAL(9, 2) NULL,
    VALOR_PACOTE DECIMAL(11, 2) NULL
);

CREATE TABLE AMB_CONVENIO (
    COD_AMB CHARACTER(8) NOT NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    DATA_CADASTRO DATE NULL,
    OBS VARCHAR(100) NULL,
    PERC_AUTOGERADO SMALLINT NULL,
    PERC_DESCONTO SMALLINT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_DESCONTO DECIMAL(11, 2) NULL,
    VALOR_PACOTE DECIMAL(11, 2) NULL,
    VALOR_PROCEDIMENTO DECIMAL(11, 2) NULL
);

CREATE TABLE AMB_CREDENCIADO (
    COD_CREDENCIADO VARCHAR(8) NOT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NOT NULL,
    DATA_CADASTRO DATE NULL,
    USUARIO VARCHAR(10) NULL
);

CREATE TABLE AMB_ESPECIALIDADE (
    COD_ESPECIALIDADE SMALLINT NOT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    USUARIO VARCHAR(10) NOT NULL
);

CREATE TABLE ASSUNTO_PROCESSO (
    COD_ASSUNTO SMALLINT NOT NULL,
    DESC_ASSUNTO VARCHAR(40) NOT NULL
);

CREATE TABLE AUSENCIA (
    COD_CREDENCIADO VARCHAR(8) NOT NULL,
    COD_TIPO_LOCAL SMALLINT NOT NULL,
    DATA_CADASTRO DATE NULL,
    DATA_FIM DATE NULL,
    DATA_INICIO DATE NOT NULL,
    HORA TIME(3) NULL,
    MOTIVO VARCHAR(25) NULL,
    USUARIO VARCHAR(10) NULL
);

CREATE TABLE AUTORIZ_CASSE (
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_PROCEDIMENTO VARCHAR(8) NULL,
    DATA_AUTORIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    MATRICULA VARCHAR(7) NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    NUM_SEQ_DEPEND SMALLINT NULL,
    NUM_SESSOES SMALLINT NULL,
    NUM_TRATAMENTO INTEGER NOT NULL,
    SENHA_AUTORIZADOR VARCHAR(10) NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    STATUS_GUIA CHARACTER(1) NULL,
    TIPO_GUIA SMALLINT NOT NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE AUTORIZ_TRATAMENTO (
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_PROCEDIMENTO VARCHAR(8) NULL,
    DATA_AUTORIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    MATRICULA VARCHAR(7) NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    NUM_SEQ_DEPEND SMALLINT NULL,
    NUM_SESSOES SMALLINT NULL,
    NUM_TRATAMENTO INTEGER NOT NULL,
    SENHA_AUTORIZADOR VARCHAR(10) NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    STATUS_GUIA CHARACTER(1) NULL,
    TIPO_GUIA SMALLINT NOT NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE BANCO (
    COD_BANCO VARCHAR(3) NOT NULL,
    DESC_BANCO VARCHAR(30) NOT NULL
);

CREATE TABLE BEM_IMOVEL (
    AREA VARCHAR(5) NULL,
    BAIRRO VARCHAR(25) NULL,
    CEP VARCHAR(9) NULL,
    COD_LOCAL SMALLINT NOT NULL,
    DESC_IMOVEL VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(40) NOT NULL,
    ESTADO CHARACTER(1) NULL,
    LOCALIZACAO CHARACTER(1) NULL,
    NUM_IMOVEL SMALLINT NOT NULL,
    OBSERVACAO VARCHAR(100) NULL
);

CREATE TABLE BEM_MOVEL (
    ACHOU SMALLINT NULL,
    COD_ELEN_CONT VARCHAR(9) NULL,
    COD_GRUPO SMALLINT NULL,
    COD_LEVANT CHARACTER(1) NULL,
    DATA_CADASTRO DATE NULL,
    DATA_EMPENHO DATE NULL,
    DESC_PATRIMONIO VARCHAR(60) NULL,
    MOTIVO_EXCL VARCHAR(20) NULL,
    NOME_FABRIC VARCHAR(40) NULL,
    NUM_EMPENHO VARCHAR(8) NULL,
    NUM_NOTA VARCHAR(10) NULL,
    NUM_PATRIMONIO INTEGER NOT NULL,
    NUM_PROC_AQUIS VARCHAR(10) NULL,
    NUM_PROC_EXCL VARCHAR(10) NULL,
    PROC_BAIXA VARCHAR(10) NULL,
    SIT_MOVEL VARCHAR(8) NULL,
    TIPO_ENTRADA VARCHAR(1) NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_AQUIS DECIMAL(9, 2) NULL,
    VALOR_NOVO DECIMAL(9, 2) NULL
);

CREATE TABLE BENEF_AUX_DOENCA (
    ANO_MES VARCHAR(6) NULL,
    COD_INT_DOENCAS INTEGER NULL,
    DATA_PB DATE NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    NUMERO_PB INTEGER NULL,
    OBSERVACAO CHARACTER(60) NULL,
    PERIODO_FINAL DATE NULL,
    PERIODO_INICIAL DATE NULL,
    QUANTIDADE_DIAS SMALLINT NULL,
    VALOR DECIMAL(14, 2) NULL,
    VALOR_SM DECIMAL(8, 2) NULL
);

CREATE TABLE BENEF_BCO_REQ (
    COD_AGENCIA VARCHAR(5) NULL,
    COD_BANCO VARCHAR(3) NULL,
    DV_CONTA VARCHAR(2) NULL,
    MATRIC_FOLHA VARCHAR(10) NULL,
    NOME VARCHAR(50) NULL,
    NUM_CONTA VARCHAR(10) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_REQUERENTE INTEGER NOT NULL,
    TAB VARCHAR(1) NOT NULL
);

CREATE TABLE BENEF_CARGO (
    CLASSE VARCHAR(6) NULL,
    COD_CARGO VARCHAR(6) NOT NULL,
    COD_REGIME SMALLINT NULL,
    COMISSAO VARCHAR(6) NULL,
    INCORPORADO CHARACTER(1) NULL,
    MES_SALARIO VARCHAR(6) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    ORGAO_ORIGEM INTEGER NULL,
    PERC_MAIS DECIMAL(5, 2) NULL,
    PERC_PADRAO DECIMAL(5, 2) NULL,
    PERC_SAL_MINIMO DECIMAL(5, 2) NULL,
    REFERENCIA VARCHAR(6) NULL,
    REPARTICAO VARCHAR(30) NULL,
    ULT_VENCTO_BASE DECIMAL(14, 2) NULL
);

CREATE TABLE BENEF_DEPENDENTE (
    COD_BENEF VARCHAR(7) NOT NULL,
    COD_PRI_ORGAO SMALLINT NOT NULL,
    COD_SITUACAO SMALLINT NULL,
    COTA_RETIDA CHARACTER(1) NULL,
    DATA_EXCLUSAO DATE NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    NUM_SEQ_DEPENDE SMALLINT NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    PERCENTUAL DECIMAL(7, 4) NULL,
    PROC_CONC VARCHAR(10) NULL,
    VALOR DECIMAL(14, 2) NULL
);

CREATE TABLE BENEF_FINANCEIRO (
    ANO VARCHAR(4) NOT NULL,
    MATRICULA VARCHAR(10) NOT NULL,
    MES INTEGER NOT NULL,
    REFERENCIA INTEGER NOT NULL,
    RUBRICA INTEGER NOT NULL,
    VALOR DECIMAL(12, 2) NOT NULL,
    VALOR_CALCULADO DECIMAL(12, 2) NULL
);

CREATE TABLE BENEF_FINANCEIRO_CADASTRO (
    MATRICULA VARCHAR(10) NOT NULL,
    NOME VARCHAR(60) NULL
);

CREATE TABLE BENEF_FOLHA_PAG (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_TIPO_BENEF SMALLINT NOT NULL,
    QTD_BENEF SMALLINT NULL,
    VALOR DECIMAL(11, 2) NULL
);

CREATE TABLE BENEF_HIST_RUBRICA (
    ANO_MES CHARACTER(6) NOT NULL,
    CLASSE VARCHAR(6) NULL,
    COD_CARGO VARCHAR(6) NOT NULL,
    COD_RUBRICA INTEGER NULL,
    COTA CHARACTER(1) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    OBSERVACAO VARCHAR(50) NULL,
    PERCENTUAL DECIMAL(6, 2) NULL,
    PERCENTUAL_MAIS DECIMAL(5, 2) NULL,
    PERCENTUAL_PADRAO DECIMAL(5, 2) NULL,
    REFERENCIA VARCHAR(6) NULL,
    VALOR DECIMAL(14, 2) NULL,
    VALOR_CAL_MAIS DECIMAL(14, 2) NULL,
    VALOR_CALCULADO DECIMAL(14, 2) NULL
);

CREATE TABLE BENEF_HISTORICO (
    COMENTARIO VARCHAR(40) NULL,
    DATA_HISTORICO DATE NOT NULL,
    HISTORICO LONG VARCHAR(32700) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL
);

CREATE TABLE BENEF_INDEFER (
    CODIGO_INDEFER INTEGER NOT NULL,
    DESCRICAO_INDEFER VARCHAR(30) NULL
);

CREATE TABLE BENEF_INDICES (
    ANO_MES VARCHAR(6) NOT NULL,
    DIA VARCHAR(2) NOT NULL,
    VALOR DECIMAL(20, 4) NULL
);

CREATE TABLE BENEF_LEIS (
    COD_LEI SMALLINT NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL
);

CREATE TABLE BENEF_PB (
    ANO_MES_REF VARCHAR(6) NOT NULL,
    DATA_PB DATE NOT NULL,
    NUM_PB INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    VALOR_PB DECIMAL(14, 2) NOT NULL
);

CREATE TABLE BENEF_PROCESSO (
    ALTERA VARCHAR(15) NULL,
    COD_AGENCIA VARCHAR(5) NULL,
    COD_BANCO VARCHAR(3) NULL,
    COD_BENEF VARCHAR(7) NULL,
    COD_INDEFERE SMALLINT NULL,
    COD_INT_DOENCA INTEGER NULL,
    COD_MOT_TERM SMALLINT NULL,
    COD_MUNICIPIO SMALLINT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_TIPO_BENEF SMALLINT NULL,
    CONCESSAO VARCHAR(15) NULL,
    DATA_AFAST DATE NULL,
    DATA_ALTERA DATE NULL,
    DATA_CONCESSAO DATE NULL,
    DATA_DEFERE DATE NULL,
    DATA_PAG_BANCO DATE NULL,
    DATA_PUBLICA DATE NULL,
    DATA_VALIDADE DATE NULL,
    DEFERE_STATUS SMALLINT NULL,
    DIG_VER_CONTA VARCHAR(2) NULL,
    DT_ADMISSAO DATE NULL,
    DT_DEMISSAO DATE NULL,
    DT_OBITO DATE NULL,
    DT_RECLUSAO_FIN DATE NULL,
    DT_RECLUSAO_INI DATE NULL,
    DT_TERM_BENEF DATE NULL,
    LIC_PRORROG CHARACTER(1) NULL,
    MATR_CADAST VARCHAR(8) NULL,
    MATR_FOLHA_PGTO VARCHAR(10) NULL,
    NUM_CONTA VARCHAR(10) NULL,
    NUM_NOTA VARCHAR(15) NULL,
    NUM_PAG_BANCO VARCHAR(10) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_REQUERENTE INTEGER NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    ORGAO_ORIGEM INTEGER NULL,
    PER_BEN_FIM DATE NULL,
    PER_BEN_INI DATE NULL,
    PROC_APENSADO VARCHAR(10) NULL,
    PROCESSO_ANT VARCHAR(8) NULL,
    PUBLICA VARCHAR(15) NULL,
    RECLUSAO VARCHAR(7) NULL,
    TIPO_BENEF SMALLINT NULL,
    VALOR DECIMAL(14, 2) NULL,
    VALOR_FUNERAL DECIMAL(14, 2) NULL
);

CREATE TABLE BENEF_PROVENTO (
    COD_CARGO VARCHAR(6) NOT NULL,
    COEFICIENTE DECIMAL(10, 6) NULL,
    MES_ANO VARCHAR(6) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQUENCIA SMALLINT NOT NULL,
    TIPO_MOEDA VARCHAR(5) NULL,
    VALOR DECIMAL(14, 2) NULL,
    VALOR_TOTAL DECIMAL(10, 2) NULL,
    VENCTO_BASE DECIMAL(14, 2) NULL
);

CREATE TABLE BENEF_RENDIMENTOS (
    ANO_EXERCICIO VARCHAR(4) NULL,
    CENTROCUSTO DECIMAL(10, 2) NULL,
    CONTRPREVOFICIAL DECIMAL(10, 2) NULL,
    CONTRPREVPRIVADA DECIMAL(10, 2) NULL,
    CPF VARCHAR(11) NOT NULL,
    DECIMOTERCEIRO DECIMAL(10, 2) NULL,
    DEPPENSAO VARCHAR(60) NULL,
    DIARIAS DECIMAL(10, 2) NULL,
    FILLER VARCHAR(10) NULL,
    IMPOSTORENDA DECIMAL(10, 2) NULL,
    LUCROS DECIMAL(10, 2) NULL,
    NOME VARCHAR(50) NULL,
    OUTROS DECIMAL(10, 2) NULL,
    OUTROS2 DECIMAL(10, 2) NULL,
    PARCISENTA DECIMAL(10, 2) NULL,
    PENSAOALIMENTICIA DECIMAL(10, 2) NULL,
    PENSAOPROV DECIMAL(10, 2) NULL,
    REDIMENTOS DECIMAL(10, 2) NULL,
    SALARIOFAMILIA DECIMAL(10, 2) NULL,
    VALPAGOSTIT DECIMAL(10, 2) NULL
);

CREATE TABLE BENEF_REQUERENTE (
    BAIRRO VARCHAR(20) NULL,
    CEP VARCHAR(8) NULL,
    COD_AGENCIA VARCHAR(5) NULL,
    COD_BANCO VARCHAR(3) NULL,
    COD_CIDADE SMALLINT NULL,
    COD_TIPO_DEPEN SMALLINT NULL,
    CPF VARCHAR(11) NULL,
    DATA_NASCIMENTO DATE NULL,
    DV_CONTA VARCHAR(2) NULL,
    ENDERECO VARCHAR(50) NULL,
    MATRIC_FPAGTO VARCHAR(10) NULL,
    NOME VARCHAR(40) NULL,
    NUM_CONTA VARCHAR(10) NULL,
    NUM_REQUERENTE INTEGER NOT NULL,
    RG_NUM VARCHAR(15) NULL,
    RG_ORGAO_EXP VARCHAR(6) NULL,
    TELEFONE VARCHAR(15) NULL
);

CREATE TABLE BENEF_RUB_MEDIA (
    ANO_MES VARCHAR(6) NULL,
    CLASSE VARCHAR(6) NULL,
    COD_CARGO VARCHAR(6) NOT NULL,
    COD_RUBRICA INTEGER NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    REFERENCIA VARCHAR(6) NULL,
    VALOR DECIMAL(11, 2) NULL
);

CREATE TABLE BENEF_RUBRICA (
    COD_CARGO VARCHAR(6) NOT NULL,
    COD_RUBRICA INTEGER NOT NULL,
    COTA CHARACTER(1) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    PERCENTUAL DECIMAL(6, 2) NULL,
    VALOR DECIMAL(14, 2) NULL,
    VALOR_CALCULADO DECIMAL(14, 2) NULL
);

CREATE TABLE BENEF_RUBRICA_CAL (
    CARGO_COMISSAO SMALLINT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_RUBRICA INTEGER NOT NULL,
    COTA_MULTIPLIC DECIMAL(10, 2) NULL,
    DEB_CREDITO SMALLINT NULL,
    PERCENTUAL DECIMAL(6, 2) NULL,
    SEQUENCIA INTEGER NOT NULL,
    TIPO_CALCULO INTEGER NULL,
    VLR_FIXO DECIMAL(10, 2) NULL
);

CREATE TABLE BENEF_RUBRICA_LEI (
    COD_ORGAO SMALLINT NOT NULL,
    COD_RUBRICA SMALLINT NOT NULL,
    DESC_LEI VARCHAR(120) NULL
);

CREATE TABLE BENEF_TIPOBEN (
    COD_TIPO_BEN SMALLINT NOT NULL,
    DESC_TIPO_BEN VARCHAR(40) NULL,
    TIPO_CALCULO SMALLINT NOT NULL
);

CREATE TABLE BENEF_TIPORUBRICA (
    CODIGO_RUBRICA INTEGER NOT NULL,
    DESCRICAO_RUBRICA VARCHAR(30) NULL
);

CREATE TABLE BOLETIM_DES (
    MATRICULA VARCHAR(7) NOT NULL,
    MES_ANO CHARACTER(6) NOT NULL,
    PA1 DECIMAL(5, 2) NULL,
    PA2 DECIMAL(5, 2) NULL,
    PA3 DECIMAL(5, 2) NULL,
    PA4 DECIMAL(5, 2) NULL,
    PA5 DECIMAL(5, 2) NULL,
    PA6 DECIMAL(5, 2) NULL
);

CREATE TABLE CAPA_INFORMIX (
    ANEXO VARCHAR(40) NULL,
    ANO_MES CHARACTER(10) NULL,
    ASSUNTO VARCHAR(40) NULL,
    COD_CREDENCIADO CHARACTER(8) NULL,
    DATA_PAGTO DATE NULL,
    DATA_RECEBIMENTO DATE NULL,
    DATA_REMESSA DATE NULL,
    DATA_ULT_ATUALIZ DATE NULL,
    DESCONTO_CH INTEGER NULL,
    MATR_FUNC_ULT_ATUA CHARACTER(7) NULL,
    MES_ANO_REF CHARACTER(4) NULL,
    MUNICIPIO CHARACTER(3) NULL,
    NOME VARCHAR(50) NULL,
    NUM_PROCESSO CHARACTER(10) NULL,
    NUM_RELACAO_PAG CHARACTER(9) NULL,
    NUM_SEGURADO INTEGER NULL,
    NUM_VIAS_EMITIDAS CHARACTER(2) NULL,
    OBSERVACAO VARCHAR(60) NULL,
    PROC_APENSADO CHARACTER(8) NULL,
    RECIPROCIDADE CHARACTER(1) NULL,
    SITUACAO_PROCESSO CHARACTER(1) NULL,
    TIPO_APOSENT CHARACTER(5) NULL,
    TIPO_BENEF CHARACTER(5) NULL,
    TIPO_PROCESSO CHARACTER(1) NULL,
    TOT_GERAL_GUIAS SMALLINT NULL,
    TOT_GUIA_AMB SMALLINT NULL,
    TOT_GUIA_AUXILIAR SMALLINT NULL,
    TOT_GUIA_CONSULTA SMALLINT NULL,
    TOT_GUIA_EXAME SMALLINT NULL,
    TOT_GUIA_INTERNAC SMALLINT NULL,
    TOT_GUIA_INV_AMB SMALLINT NULL,
    TOT_GUIA_INVALID SMALLINT NULL,
    TOT_GUIA_MATERIAL SMALLINT NULL,
    TOT_GUIA_TAREFA SMALLINT NULL,
    VL_AUTORIZ_URV DECIMAL(8, 2) NULL,
    VL_AUTORIZADO DECIMAL(12, 2) NULL,
    VLR_ACRESCIMO DECIMAL(12, 2) NULL,
    VLR_DESCONTO DECIMAL(12, 2) NULL,
    VLR_GLOSADO DECIMAL(12, 2) NULL,
    VLR_IR DECIMAL(12, 2) NULL,
    VLR_REQUERIDO DECIMAL(12, 2) NULL
);

CREATE TABLE CAPA_PROCESSO (
    ANEXO VARCHAR(50) NULL,
    ANO_MES CHARACTER(6) NULL,
    ASSUNTO VARCHAR(50) NULL,
    COD_ASSUNTO SMALLINT NULL,
    COD_CREDENCIADO CHARACTER(8) NULL,
    COD_MUNICIPIO SMALLINT NULL,
    DATA_CADASTRO DATE NULL,
    NOME VARCHAR(50) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_RELACAO_PAG VARCHAR(9) NULL,
    NUM_SEGURADO INTEGER NULL,
    OBSERVACAO VARCHAR(60) NULL,
    RECIPROCIDADE CHARACTER(1) NULL,
    SITUACAO_PROCESSO CHARACTER(1) NULL,
    TIPO_PROCESSO CHARACTER(1) NULL,
    TOT_GERAL_GUIAS SMALLINT NULL,
    TOT_GUIA_AMBULA SMALLINT NULL,
    TOT_GUIA_AUXILIAR SMALLINT NULL,
    TOT_GUIA_CONSULTA SMALLINT NULL,
    TOT_GUIA_EXAME SMALLINT NULL,
    TOT_GUIA_INTERNAC SMALLINT NULL,
    TOT_GUIA_INV_AMBU SMALLINT NULL,
    TOT_GUIA_INVALIDAS SMALLINT NULL,
    TOT_GUIA_MATERIAL SMALLINT NULL,
    TOT_GUIA_TAREFA SMALLINT NULL,
    USUARIO VARCHAR(15) NULL,
    VLR_ACRESCIMO DECIMAL(11, 2) NULL,
    VLR_DESCONTO DECIMAL(11, 2) NULL,
    VLR_GLOSADO DECIMAL(11, 2) NULL,
    VLR_IR DECIMAL(11, 2) NULL,
    VLR_LIQ_CALCULADO DECIMAL(11, 2) NULL,
    VLR_REQUERIDO DECIMAL(11, 2) NULL,
    VLR_URV_CALCULADO DECIMAL(11, 2) NULL
);

CREATE TABLE CARTORARIO (
    CARGO CHARACTER(5) NOT NULL,
    COD_CARTORIO SMALLINT NOT NULL,
    COD_MUNICIPIO SMALLINT NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    DATA_DEMISSAO DATE NULL,
    MOT_EXCLUSAO VARCHAR(20) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PERCENTUAL DECIMAL(6, 2) NOT NULL,
    QTDE_MVRE SMALLINT NULL,
    SALARIO DECIMAL(10, 2) NOT NULL,
    TIPO_VINCULO CHARACTER(1) NOT NULL,
    VALOR_CONT DECIMAL(10, 2) NOT NULL
);

CREATE TABLE CARTORIO (
    BAIRRO VARCHAR(15) NULL,
    CEP CHARACTER(9) NULL,
    COD_CARTORIO SMALLINT NOT NULL,
    COD_MUNICIPIO SMALLINT NOT NULL,
    DESC_CARTORIO VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(30) NULL,
    SUBSTITUTO_1 VARCHAR(30) NULL,
    SUBSTITUTO_2 VARCHAR(30) NULL,
    SUBSTITUTO_3 VARCHAR(30) NULL,
    TITULAR VARCHAR(30) NOT NULL
);

CREATE TABLE CATEG_SIAFEM (
    COD_CATEGORIA CHARACTER(3) NULL,
    COD_SIAFEM VARCHAR(7) NOT NULL,
    DESCRICAO VARCHAR(30) NULL
);

CREATE TABLE CATEGORIA (
    COD_CATEGORIA SMALLINT NOT NULL,
    DESC_CATEGORIA VARCHAR(30) NULL
);

CREATE TABLE CEDIDOS (
    COD_ORGAO_CED SMALLINT NOT NULL,
    COD_ORGAO_DEST SMALLINT NOT NULL,
    DATA_CED DATE NOT NULL,
    DATA_RETORNO DATE NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    OBS VARCHAR(60) NULL
);

CREATE TABLE CEDULA_C (
    COD_CREDENCIADO CHARACTER(8) NULL,
    MES SMALLINT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_BRUTO DECIMAL(11, 2) NULL,
    VALOR_IR DECIMAL(7, 2) NULL
);

CREATE TABLE CHAVE (
    AUTORIZ_TRATAMENTO INTEGER NULL,
    BENEF_RUB_CAL INTEGER NULL,
    COD_FORNECEDOR INTEGER NULL,
    COD_LOCAL_ATEND SMALLINT NULL,
    COD_PARTE INTEGER NULL,
    COD_PRODUTO SMALLINT NULL,
    NUM_BEM_MOVEL INTEGER NULL,
    NUM_CONTRATO_PLANO INTEGER NOT NULL,
    NUM_DISCO INTEGER NULL,
    NUM_LANCTO_ADM INTEGER NULL,
    NUM_LANCTO_ODO INTEGER NULL,
    NUM_PLANILHA INTEGER NULL,
    NUM_PLANILHA_ORC INTEGER NULL,
    NUM_PROC CHARACTER(15) NULL,
    NUM_PROCESSO INTEGER NULL,
    NUM_RELACAO_PAG INTEGER NOT NULL,
    NUM_REQUISICAO_MAT SMALLINT NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_ENTREGA_DOC INTEGER NULL,
    SEQ_FOLHA_FREQ INTEGER NULL,
    SEQ_G_URGENCIA INTEGER NULL,
    SEQ_HIST_PESSOAL INTEGER NULL,
    SEQ_MOV_VEIC INTEGER NULL
);

CREATE TABLE CHAVE_AMBULATORIO (
    NUM_RECIBO INTEGER NULL
);

CREATE TABLE CHAVE_CONTRIBUINTE (
    RETENSAO_FOLHA INTEGER NULL,
    SEQ_PAGAMENTO INTEGER NULL
);

CREATE TABLE CHAVE_TABELAS (
    ID_CAMPO VARCHAR(15) NOT NULL,
    PROX_SEQ INTEGER NOT NULL
);

CREATE TABLE CID (
    COD_CID VARCHAR(8) NOT NULL,
    DESC_CID VARCHAR(60) NULL
);

CREATE TABLE CLASSE_PRODUTO (
    CLASSE SMALLINT NOT NULL,
    DESCRICAO VARCHAR(30) NULL
);

CREATE TABLE COEF_HONORARIO (
    ANO_MES CHARACTER(6) NOT NULL,
    DATA_CADASTRO DATE NULL,
    USUARIO_CADASTRO CHARACTER(10) NULL,
    VALOR_CH_PREVISUL DECIMAL(9, 2) NULL,
    VALOR_CH_RECIPROC DECIMAL(9, 2) NULL,
    VALOR_FILME DECIMAL(9, 2) NULL,
    VALOR_FILME_2 DECIMAL(9, 2) NULL
);

CREATE TABLE CONT_HISTRUBRICA (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_RUBRICA INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PERCENTUAL DECIMAL(6, 2) NULL,
    VALOR DECIMAL(10, 2) NULL,
    VALOR_PERCENT DECIMAL(10, 2) NULL
);

CREATE TABLE CONT_REF_CONTRIB (
    ANO_MES VARCHAR(6) NOT NULL,
    VALOR DECIMAL(6, 2) NULL
);

CREATE TABLE CONT_RUBRICA (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_RUBRICA INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PERCENTUAL DECIMAL(6, 2) NULL,
    VALOR DECIMAL(10, 2) NULL,
    VALOR_PERCENT DECIMAL(10, 2) NULL
);

CREATE TABLE CONT_TAXAS (
    DATA DATE NOT NULL,
    JUROS DECIMAL(5, 2) NULL,
    MULTA DECIMAL(5, 2) NULL
);

CREATE TABLE CONTRATO_CREDENC (
    COD_CATEGORIA SMALLINT NOT NULL,
    SEQUENCIA SMALLINT NULL,
    TEXTO LONG VARCHAR(32700) NULL,
    TITULO LONG VARCHAR(32700) NULL
);

CREATE TABLE CONTRATO_IMOVEL (
    COD_FORNECEDOR SMALLINT NOT NULL,
    DATA_ASSINATURA DATE NULL,
    DATA_DISPENSA DATE NULL,
    DATA_EMPENHO DATE NULL,
    DATA_ENVIO_TC DATE NULL,
    DATA_EXTRATO DATE NULL,
    DATA_FIM DATE NULL,
    DATA_INICIO DATE NULL,
    DISPENSA VARCHAR(10) NULL,
    EXTRATO VARCHAR(10) NULL,
    INDICE VARCHAR(10) NULL,
    NUM_CONTRATO INTEGER NOT NULL,
    NUM_EMPENHO VARCHAR(10) NULL,
    NUM_IMOVEL INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    OBSERVACAO VARCHAR(100) NULL,
    PRAZO VARCHAR(1) NULL,
    PROCESSO_ENCERRA VARCHAR(40) NULL,
    VALOR_CONTRATO DECIMAL(9, 2) NULL
);

CREATE TABLE CONTRIB_ALTER_BOLETO (
    ANO_MES CHARACTER(6) NOT NULL,
    DATA_ALTERACAO DATE NOT NULL,
    NUM_BOLETO VARCHAR(15) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_PAGAMENTO INTEGER NOT NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE CONTRIB_PLANILHA (
    ANO_MES VARCHAR(6) NOT NULL,
    COD_CARTORIO INTEGER NOT NULL,
    COD_MUNICIPIO INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PREC_CONTRIB DECIMAL(5, 2) NULL,
    PREC_JUROS DECIMAL(5, 2) NULL,
    PREC_MULTA DECIMAL(5, 2) NULL,
    QDT_MVRE INTEGER NULL,
    SAL_CONTRIB DECIMAL(12, 2) NULL,
    VLR_CONTRIB DECIMAL(12, 2) NULL,
    VLR_JUROS DECIMAL(12, 2) NULL,
    VLR_MULTA DECIMAL(12, 2) NULL
);

CREATE TABLE CONTRIBUINTE (
    CANCEL CHARACTER(1) NULL,
    CARG_COMISSAO CHARACTER(1) NULL,
    CLASSE VARCHAR(10) NULL,
    CLASSE_COMISSAO VARCHAR(10) NULL,
    COD_CARGO VARCHAR(6) NULL,
    COD_CARGO_COMISSAO VARCHAR(6) NULL,
    COD_ORGAO SMALLINT NULL,
    DATA_CANCEL DATE NULL,
    DATA_DEFERE DATE NULL,
    DEFERE CHARACTER(1) NULL,
    INICIO_CONTRIB CHARACTER(6) NOT NULL,
    MOTIVO_CANCEL VARCHAR(30) NULL,
    MOTIVO_INDEF VARCHAR(100) NULL,
    NUM_DEP_COB INTEGER NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEG_COB INTEGER NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PERCENTUAL DECIMAL(6, 2) NOT NULL,
    REF VARCHAR(10) NULL,
    REF_COMISSAO VARCHAR(10) NULL,
    TIPO_CONTRIBUINTE CHARACTER(1) NOT NULL,
    VALOR_CONT DECIMAL(10, 2) NOT NULL
);

CREATE TABLE CREDENC_CONT_BANC (
    COD_AGENCIA VARCHAR(5) NULL,
    COD_BANCO VARCHAR(3) NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    DATA_CADASTRO DATE NULL,
    DV_CTA_CORRENTE CHARACTER(2) NULL,
    NUM_CTA_CORRENTE VARCHAR(12) NULL,
    STATUS INTEGER NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE CREDENC_HISTORICO (
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    DATA_ATIVACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_DESATIVACAO DATE NULL,
    INFORMANTE_ATIV VARCHAR(40) NULL,
    INFORMANTE_DESAT VARCHAR(40) NULL,
    MOTIVO VARCHAR(150) NULL,
    OBSERVACAO VARCHAR(200) NULL,
    SITUACAO INTEGER NULL
);

CREATE TABLE CREDENC_PROCED (
    COD_AMB VARCHAR(8) NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    DATA_CADASTRO DATE NULL,
    DATA_CANCELAMENTO DATE NULL,
    STATUS SMALLINT NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE CREDENCIADO (
    AGENTE_REGIONAL VARCHAR(40) NULL,
    BAIRRO VARCHAR(35) NULL,
    CELULAR VARCHAR(25) NULL,
    CEP VARCHAR(10) NULL,
    CLASSE_HOSPITAL SMALLINT NULL,
    CNPJ VARCHAR(15) NULL,
    COD_CATEGORIA SMALLINT NULL,
    COD_CIDADE_END SMALLINT NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    COD_ESPEC_PRINC SMALLINT NULL,
    COD_ESPEC_SECUND SMALLINT NULL,
    COD_MUNICIPIO_CRED SMALLINT NULL,
    CPF VARCHAR(15) NULL,
    DATA_ADMISSAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_DIPLOMACAO DATE NULL,
    DATA_ISS DATE NULL,
    DATA_NASCIMENTO DATE NULL,
    DATA_PROCESSO DATE NULL,
    DESCONTO_ESPECIAL SMALLINT NULL,
    DESCONTO_VINCULO SMALLINT NULL,
    DIRETOR_AREA VARCHAR(40) NULL,
    DIRETOR_GERAL VARCHAR(40) NULL,
    DOCUMENTOS VARCHAR(200) NULL,
    EFETIVO SMALLINT NULL,
    END_ELETRONICO VARCHAR(60) NULL,
    ENDERECO VARCHAR(40) NULL,
    ESTADO_CIVIL SMALLINT NULL,
    INSC_ESTADUAL VARCHAR(15) NULL,
    INSC_MUNICIPAL VARCHAR(15) NULL,
    ISENTO_IR SMALLINT NULL,
    ISENTO_ISS SMALLINT NULL,
    NATURALIDADE VARCHAR(40) NULL,
    NOME VARCHAR(40) NOT NULL,
    NOME_CONJUGE VARCHAR(40) NULL,
    NOME_MAE VARCHAR(40) NULL,
    NOME_PAI VARCHAR(40) NULL,
    NUM_CONS_REG VARCHAR(10) NULL,
    NUM_CONTRATO VARCHAR(10) NULL,
    NUM_PROCESSO VARCHAR(8) NULL,
    OBS_CADASTRAIS VARCHAR(200) NULL,
    OBS_CONTRATO VARCHAR(200) NULL,
    ORGAO_EMISSOR_DIP VARCHAR(40) NULL,
    PERCENT_ACRESCIMO DECIMAL(5, 2) NULL,
    PERCENT_DESCONTO DECIMAL(5, 2) NULL,
    PERITO_JUNTA SMALLINT NULL,
    QUANT_DEPEND SMALLINT NULL,
    RAZAO_SOCIAL VARCHAR(40) NULL,
    RESPONSAVEL_SETOR VARCHAR(40) NULL,
    RG VARCHAR(20) NULL,
    SEXO SMALLINT NULL,
    TELEFONE VARCHAR(25) NULL,
    TETO SMALLINT NULL,
    TIPO_PESSOA SMALLINT NULL,
    UF CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_ACRESCIMO DECIMAL(9, 2) NULL,
    VALOR_DESCONTO DECIMAL(9, 2) NULL
);

CREATE TABLE DEB_EXOFICIO (
    COD_AGENCIA VARCHAR(5) NULL,
    COD_BANCO VARCHAR(3) NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    DV_CONTA VARCHAR(2) NULL,
    ESPECIE CHARACTER(1) NOT NULL,
    NOME VARCHAR(30) NULL,
    NUM_CONTA VARCHAR(8) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_RELACAO VARCHAR(9) NULL,
    VALOR_EXOFICIO DECIMAL(9, 2) NULL,
    VALOR_IR DECIMAL(9, 2) NULL,
    VALOR_PAGO DECIMAL(11, 2) NULL
);

CREATE TABLE DEB_PROC_ADM (
    COD_FORNECEDOR INTEGER NULL,
    DATA_NF DATE NULL,
    DATA_PAGTO DATE NULL,
    DATA_VCTO DATE NULL,
    DT_ULT_ALTER DATE NULL,
    ELEMENTO_DESPESA CHARACTER(8) NULL,
    ESPECIE CHARACTER(1) NULL,
    ESPECIFI_DESPESA CHARACTER(60) NULL,
    MODELO_NF CHARACTER(1) NULL,
    NOME_FORNECEDOR CHARACTER(30) NULL,
    NUM_LANCTO INTEGER NULL,
    NUM_NF CHARACTER(10) NULL,
    NUM_PROCESSO CHARACTER(10) NULL,
    SERIE_NF CHARACTER(1) NULL,
    TIPO_DESPESA CHARACTER(1) NULL,
    TIPO_MOVTO CHARACTER(1) NULL,
    ULT_ALTEROU CHARACTER(8) NULL,
    VALOR_DESPESA DECIMAL(11, 2) NULL,
    VALOR_ISS DECIMAL(9, 2) NULL,
    VALOR_PAGO DECIMAL(11, 2) NULL,
    VLR_IR DECIMAL(9, 2) NULL
);

CREATE TABLE DEBITO (
    ANO_MES VARCHAR(6) NOT NULL,
    COD_AGENCIA CHARACTER(5) NULL,
    COD_BANCO CHARACTER(3) NULL,
    COD_CATEGORIA SMALLINT NULL,
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_FORNECEDOR SMALLINT NULL,
    COD_MUNICIPIO SMALLINT NULL,
    COD_TIPO_BENEF SMALLINT NULL,
    DATA_CADASTRO DATE NULL,
    DATA_NF DATE NULL,
    DATA_NL DATE NULL,
    DATA_OB DATE NULL,
    DATA_PAGTO DATE NULL,
    DATA_VENCTO DATE NULL,
    DV_CONTA CHARACTER(2) NULL,
    ELEMENTO_DESPESA VARCHAR(8) NULL,
    ESPECIE CHARACTER(1) NULL,
    ESPECIFI_DESPESA VARCHAR(60) NULL,
    GERADO_POR VARCHAR(15) NULL,
    MODELO_NF CHARACTER(1) NULL,
    NOME_CREDOR VARCHAR(50) NULL,
    NUM_CONTA VARCHAR(8) NULL,
    NUM_EMPENHO VARCHAR(9) NULL,
    NUM_LANCTO INTEGER NULL,
    NUM_NF VARCHAR(8) NULL,
    NUM_NL VARCHAR(9) NULL,
    NUM_OB VARCHAR(9) NULL,
    NUM_PB VARCHAR(10) NULL,
    NUM_PLANILHA VARCHAR(9) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_RELACAO_PAG VARCHAR(9) NULL,
    NUM_REQUERENTE INTEGER NULL,
    SERIE_NF CHARACTER(1) NULL,
    SIT_DEBITO CHARACTER(1) NULL,
    TIPO_DESPESA CHARACTER(1) NULL,
    TIPO_MOVIMENTO CHARACTER(1) NULL,
    TIPO_PROCESSO CHARACTER(1) NULL,
    VALOR_ACRESCIMO DECIMAL(9, 2) NULL,
    VALOR_DEBITO DECIMAL(9, 2) NULL,
    VALOR_DESCONTO DECIMAL(9, 2) NULL,
    VALOR_IR DECIMAL(9, 2) NULL,
    VALOR_ISS DECIMAL(9, 2) NULL,
    VALOR_PAGO DECIMAL(11, 2) NULL
);

CREATE TABLE DEPENDENTE (
    COD_BENEF CHARACTER(7) NOT NULL,
    COD_MUN_EMISSAO INTEGER NULL,
    COD_MUN_ENVIO INTEGER NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_TIPO_DEPEND SMALLINT NULL,
    DATA_ATUALIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_DEFER_PROC DATE NULL,
    DATA_EMISSAO_CART DATE NULL,
    DATA_NASCIMENTO DATE NULL,
    DATA_SITUACAO DATE NULL,
    DATA_VAL_CARTEIRA DATE NULL,
    EMITE_CARTEIRA CHARACTER(1) NULL,
    EMITIR_OFICIO CHARACTER(1) NULL,
    FAIXA_ETARIA CHARACTER(6) NULL,
    NOME VARCHAR(50) NOT NULL,
    NOME_MAE VARCHAR(45) NULL,
    NOME_PAI VARCHAR(45) NULL,
    NUM_OFICIO VARCHAR(8) NULL,
    NUM_PROC_EXCLUSAO VARCHAR(10) NULL,
    NUM_PROCESSO_INCL VARCHAR(10) NULL,
    NUM_RG VARCHAR(15) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    NUM_SEQ_DEPEND SMALLINT NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    SEXO CHARACTER(1) NULL,
    SIGLA_ORGAO_RG VARCHAR(3) NULL,
    SITUACAO_DEPEND SMALLINT NULL,
    UF_ORGAO_RG CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE DEPENDENTE_AUXILIAR (
    COD_BENEF CHARACTER(7) NOT NULL,
    COD_MUN_EMISSAO INTEGER NULL,
    COD_MUN_ENVIO INTEGER NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_SIT_SUB SMALLINT NULL,
    COD_TIPO_DEPEND SMALLINT NULL,
    DATA_ATUALIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_DEFER_PROC DATE NULL,
    DATA_EMISSAO_CART DATE NULL,
    DATA_INI_CARENCIA DATE NULL,
    DATA_NASCIMENTO DATE NULL,
    DATA_SITUACAO DATE NULL,
    DATA_VAL_CARTEIRA DATE NULL,
    EMITE_CARTEIRA CHARACTER(1) NULL,
    EMITIR_OFICIO CHARACTER(1) NULL,
    FAIXA_ETARIA CHARACTER(6) NULL,
    MOTIVO_BLOQUEIO VARCHAR(50) NULL,
    NOME VARCHAR(50) NOT NULL,
    NOME_MAE VARCHAR(45) NULL,
    NOME_PAI VARCHAR(45) NULL,
    NUM_OFICIO VARCHAR(8) NULL,
    NUM_PROC_EXCLUSAO VARCHAR(8) NULL,
    NUM_PROCESSO_INCL VARCHAR(8) NULL,
    NUM_RG VARCHAR(15) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    NUM_SEQ_DEPEND SMALLINT NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    SEXO CHARACTER(1) NULL,
    SIGLA_ORGAO_RG VARCHAR(3) NULL,
    SITUACAO_DEPEND SMALLINT NULL,
    UF_ORGAO_RG CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE DESCONTO_VINCULO (
    COD_DESCONTO INTEGER NOT NULL,
    DESC_DESCONTO VARCHAR(30) NULL
);

CREATE TABLE DETALHE_BANCO (
    AGENCIA_FAVORECIDO CHARACTER(4) NULL,
    ANO_MES VARCHAR(6) NOT NULL,
    BANCO_FAVORECIDO CHARACTER(3) NULL,
    BRANCO_10 CHARACTER(10) NULL,
    BRANCO_11 CHARACTER(14) NULL,
    BRANCO_18 CHARACTER(2) NULL,
    BRANCO_2 CHARACTER(1) NULL,
    CC_DEPOSITO_PREV VARCHAR(9) NULL,
    CC_FAVORECIDO CHARACTER(12) NULL,
    COMPENSACAO CHARACTER(3) NULL,
    CPF_CGC_CONF VARCHAR(12) NULL,
    DATA_BASE VARCHAR(6) NULL,
    DATA_OB DATE NULL,
    DV_AGENCIA_FAV CHARACTER(1) NULL,
    DV_CC_DEPOSITO CHARACTER(1) NULL,
    DV_CC_FAVORECIDO CHARACTER(1) NULL,
    DV_CPF_CGC CHARACTER(2) NULL,
    DV_PREFIXO_AG CHARACTER(1) NULL,
    INDICADOR_CONF CHARACTER(1) NULL,
    MENSAGEM CHARACTER(40) NULL,
    NOME_FAVORECIDO VARCHAR(40) NOT NULL,
    NUM_DISCO INTEGER NULL,
    NUM_OB VARCHAR(9) NULL,
    NUM_PROCESSO CHARACTER(10) NOT NULL,
    OCORRENCIA_RET CHARACTER(10) NULL,
    PREFIXO_AGENCIA CHARACTER(4) NULL,
    SEQUENCIA CHARACTER(6) NULL,
    SERVICO_FCC CHARACTER(3) NULL,
    TIPO_REGISTRO CHARACTER(1) NULL,
    VALOR DECIMAL(11, 2) NULL
);

CREATE TABLE DETALHE_XX (
    AGENCIA_FAVORECIDO CHARACTER(4) NULL,
    ANO_MES VARCHAR(6) NOT NULL,
    BANCO_FAVORECIDO CHARACTER(3) NULL,
    BRANCO_10 CHARACTER(10) NULL,
    BRANCO_11 CHARACTER(14) NULL,
    BRANCO_18 CHARACTER(2) NULL,
    BRANCO_2 CHARACTER(1) NULL,
    CC_DEPOSITO_PREV VARCHAR(9) NULL,
    CC_FAVORECIDO CHARACTER(12) NULL,
    COMPENSACAO CHARACTER(3) NULL,
    CPF_CGC_CONF VARCHAR(12) NULL,
    DATA_BASE VARCHAR(6) NULL,
    DATA_OB DATE NULL,
    DV_AGENCIA_FAV CHARACTER(1) NULL,
    DV_CC_DEPOSITO CHARACTER(1) NULL,
    DV_CC_FAVORECIDO CHARACTER(1) NULL,
    DV_CPF_CGC CHARACTER(2) NULL,
    DV_PREFIXO_AG CHARACTER(1) NULL,
    INDICADOR_CONF CHARACTER(1) NULL,
    MENSAGEM CHARACTER(40) NULL,
    NOME_FAVORECIDO VARCHAR(40) NOT NULL,
    NUM_DISCO INTEGER NULL,
    NUM_OB VARCHAR(9) NULL,
    NUM_PROCESSO CHARACTER(10) NOT NULL,
    OCORRENCIA_RET CHARACTER(10) NULL,
    PREFIXO_AGENCIA CHARACTER(4) NULL,
    SEQUENCIA CHARACTER(6) NULL,
    SERVICO_FCC CHARACTER(3) NULL,
    TIPO_REGISTRO CHARACTER(1) NULL,
    VALOR DECIMAL(11, 2) NULL
);

CREATE TABLE DIRF (
    COD_CREDENCIADO VARCHAR(8) NOT NULL,
    MES INTEGER NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    VLR_BRUTO DECIMAL(14, 2) NULL,
    VLR_IR DECIMAL(14, 2) NULL
);

CREATE TABLE DIVIDA_1998 (
    BRUTO2_DEZEMBRO DECIMAL(11, 2) NULL,
    CARTA_ACEITE CHARACTER(1) NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    CONVENIO CHARACTER(1) NULL,
    DATA_PAGTO DATE NULL,
    IR2_DEZEMBRO DECIMAL(9, 2) NULL,
    MES CHARACTER(10) NOT NULL,
    NOME CHARACTER(40) NOT NULL,
    VALOR_BRUTO DECIMAL(11, 2) NULL,
    VALOR_IR DECIMAL(9, 2) NULL,
    VALOR_PARCELA DECIMAL(11, 2) NULL
);

CREATE TABLE ELENCO_CONTABIL (
    COD_ELEN_CONT VARCHAR(9) NOT NULL,
    DESC_ELEN_CONT VARCHAR(80) NULL
);

CREATE TABLE EMPENHO (
    ANO INTEGER NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    EMPENHO INTEGER NOT NULL
);

CREATE TABLE EMPRESA (
    BAIRRO VARCHAR(20) NULL,
    CABECALHO_RELATORIO VARCHAR(80) NULL,
    CEP VARCHAR(8) NULL,
    CIDADE VARCHAR(20) NULL,
    CNPJ VARCHAR(14) NULL,
    DIRETOR_PRESIDENTE VARCHAR(40) NULL,
    ENDERECO VARCHAR(40) NULL,
    FAX VARCHAR(14) NULL,
    NOME VARCHAR(40) NULL,
    RASAO_SOCIAL VARCHAR(60) NULL,
    RODAPE_RELATORIO VARCHAR(80) NULL,
    TELEFONE VARCHAR(14) NULL,
    UF VARCHAR(2) NULL
);

CREATE TABLE ENTREGA_DOCUMENTO (
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_TIPO_DOC SMALLINT NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    NOME_RECEPTOR VARCHAR(40) NULL,
    NUM_DOC_FINAL INTEGER NULL,
    NUM_DOC_INICIAL INTEGER NULL,
    OBSERVACAO VARCHAR(150) NULL,
    QTDE_BLOCO INTEGER NULL,
    RG_RECEPTOR VARCHAR(20) NULL,
    SEQUENCIA SMALLINT NOT NULL,
    SERIE_DOC VARCHAR(10) NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE ESPEC_MEDICA (
    COD_ESPEC_MEDICA SMALLINT NOT NULL,
    DESC_ESPEC_MEDICA VARCHAR(30) NULL
);

CREATE TABLE ETIQ_FOLHA_PROC (
    DATA DATE NULL,
    FOLHA INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    TOTAL INTEGER NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE EXPLAIN_INSTANCE (
    AVG_APPLS INTEGER NOT NULL,
    BLOCK CHARACTER(1) NOT NULL,
    BUFFPAGE INTEGER NOT NULL,
    COMM_SPEED DOUBLE(8) NOT NULL,
    CPU_SPEED DOUBLE(8) NOT NULL,
    DATAJOINER CHARACTER(1) NOT NULL,
    DB2_VERSION CHARACTER(7) NOT NULL,
    DBHEAP INTEGER NOT NULL,
    EXPLAIN_OPTION CHARACTER(1) NOT NULL,
    EXPLAIN_REQUESTER VARCHAR(128) NOT NULL,
    EXPLAIN_TIME TIMESTAMP NOT NULL,
    ISOLATION CHARACTER(2) NOT NULL,
    LOCKLIST INTEGER NOT NULL,
    LOCKS_AVAIL INTEGER NOT NULL,
    MAXLOCKS SMALLINT NOT NULL,
    PARALLELISM CHARACTER(2) NOT NULL,
    QUERYOPT INTEGER NOT NULL,
    REMARKS VARCHAR(254) NULL,
    SNAPSHOT_TAKEN CHARACTER(1) NOT NULL,
    SORTHEAP INTEGER NOT NULL,
    SOURCE_NAME VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA VARCHAR(128) NOT NULL,
    SQL_TYPE CHARACTER(1) NOT NULL
);

CREATE TABLE EXPLAIN_STATEMENT (
    DELETABLE CHARACTER(1) NOT NULL,
    EXPLAIN_LEVEL CHARACTER(1) NOT NULL,
    EXPLAIN_REQUESTER VARCHAR(128) NOT NULL,
    EXPLAIN_TIME TIMESTAMP NOT NULL,
    QUERY_DEGREE INTEGER NOT NULL,
    QUERYNO INTEGER NOT NULL,
    QUERYTAG CHARACTER(20) NOT NULL,
    SECTNO INTEGER NOT NULL,
    SNAPSHOT BLOB(10485760) NULL,
    SOURCE_NAME VARCHAR(128) NOT NULL,
    SOURCE_SCHEMA VARCHAR(128) NOT NULL,
    STATEMENT_TEXT CLOB(1048576) NOT NULL,
    STATEMENT_TYPE CHARACTER(2) NOT NULL,
    STMTNO INTEGER NOT NULL,
    TOTAL_COST DOUBLE(8) NOT NULL,
    UPDATABLE CHARACTER(1) NOT NULL
);

CREATE TABLE FERIADO (
    DATA_FERIADO DATE NOT NULL,
    DESC_FERIADO VARCHAR(30) NOT NULL
);

CREATE TABLE FOLHA_FREQUENCIA (
    COD_FOLHA INTEGER NOT NULL,
    DATA_ENTREGA DATE NULL,
    DATA_ENVIO DATE NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    NUM_SEGURADO INTEGER NULL
);

CREATE TABLE FORNECEDOR (
    BAIRRO VARCHAR(20) NULL,
    CEP CHARACTER(9) NULL,
    CGC_CPF VARCHAR(14) NULL,
    CLASSE SMALLINT NULL,
    COD_AGENCIA VARCHAR(5) NULL,
    COD_BANCO VARCHAR(3) NULL,
    COD_CIDADE SMALLINT NULL,
    COD_FORNECEDOR SMALLINT NOT NULL,
    DATE_CADASTRO DATE NULL,
    DESCRICAO VARCHAR(40) NOT NULL,
    DV_CTA_CORRENTE VARCHAR(2) NULL,
    ENDERECO VARCHAR(40) NULL,
    FAX VARCHAR(14) NULL,
    INSC_ESTADUAL VARCHAR(9) NULL,
    INSC_MUNICIPAL VARCHAR(11) NULL,
    ISENTO_ISS CHARACTER(1) NULL,
    NUM_CTA_CORRENTE VARCHAR(8) NULL,
    TELEFONE VARCHAR(14) NULL,
    TIPO_PESSOA CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE FREQUENCIA (
    DATA_FREQ DATE NOT NULL,
    DATA_TERMINO DATE NULL,
    FERIAS_FIM DATE NULL,
    FERIAS_INICIO DATE NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    MIN_ATRAZO SMALLINT NULL,
    OBS VARCHAR(60) NULL,
    TIPO_FREQ SMALLINT NOT NULL
);

CREATE TABLE GLOSA (
    COD_GLOSA SMALLINT NOT NULL,
    DESC_GLOSA VARCHAR(60) NULL
);

CREATE TABLE GLOSA_AUXILIAR (
    COD_GLOSA SMALLINT NOT NULL,
    NIVEL_DATA CHARACTER(1) NOT NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SIT_GLOSA CHARACTER(1) NOT NULL
);

CREATE TABLE GLOSA_CONSULTA (
    COD_GLOSA SMALLINT NOT NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SIT_GLOSA CHARACTER(1) NOT NULL
);

CREATE TABLE GLOSA_EXAME (
    COD_GLOSA SMALLINT NOT NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SIT_GLOSA CHARACTER(1) NOT NULL
);

CREATE TABLE GLOSA_INTERNACAO (
    COD_GLOSA SMALLINT NOT NULL,
    COMPL_GLOSA VARCHAR(80) NULL,
    ESPECIE_GLOSA CHARACTER(1) NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SIT_GLOSA CHARACTER(1) NOT NULL
);

CREATE TABLE GLOSA_ODONTO (
    COD_GLOSA SMALLINT NOT NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO CHARACTER(10) NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SIT_GLOSA SMALLINT NULL
);

CREATE TABLE GRUPO (
    COD_GRUPO SMALLINT NOT NULL,
    DESCRICAO VARCHAR(40) NULL
);

CREATE TABLE GUIA_CONSULTA (
    COD_BENEF VARCHAR(7) NULL,
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_ORGAO SMALLINT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NULL,
    DATA_CADASTRO DATE NULL,
    DATA_CONSULTA DATE NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    QTDE_EXAME SMALLINT NULL,
    RETORNO CHARACTER(1) NULL,
    SEQ_SEGURADO SMALLINT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_CALCULO DECIMAL(11, 2) NULL,
    VALOR_GLOSA DECIMAL(11, 2) NULL
);

CREATE TABLE GUIA_EXAME (
    COD_BENEF VARCHAR(7) NULL,
    COD_CRED_REALIZ VARCHAR(8) NULL,
    COD_CRED_SOLIC VARCHAR(8) NULL,
    COD_ORGAO SMALLINT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NULL,
    CONTRASTE DECIMAL(11, 2) NULL,
    DATA_AUTORIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_REALIZACAO DATE NULL,
    DATA_SOLICITACAO DATE NULL,
    FUNC_AUTORIZ VARCHAR(15) NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_SEGURADO SMALLINT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_CALCULO DECIMAL(11, 2) NULL,
    VALOR_GLOSA DECIMAL(11, 2) NULL
);

CREATE TABLE GUIA_INTERNACAO (
    ACOMODACAO SMALLINT NULL,
    CID VARCHAR(15) NULL,
    COD_BENEF VARCHAR(7) NULL,
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_MEDICO VARCHAR(8) NULL,
    COD_ORGAO SMALLINT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NULL,
    DATA_ALTA DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_INTERNACAO DATE NULL,
    DATA_SOLICITACAO DATE NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_FOLHA INTEGER NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    OBS_GUIA VARCHAR(60) NULL,
    SEQ_SEGURADO SMALLINT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    TIPO_GUIA SMALLINT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_EXOF_CALC DECIMAL(11, 2) NULL,
    VALOR_GLOSA DECIMAL(11, 2) NULL,
    VALOR_HOSP_CALC DECIMAL(11, 2) NULL
);

CREATE TABLE GUIA_ODONTO (
    COD_BENEF VARCHAR(10) NULL,
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_ORGAO SMALLINT NULL,
    COD_PROCEDIMENTO VARCHAR(10) NULL,
    DATA_CADASTRO DATE NULL,
    DATA_SERVICO DATE NULL,
    FACE_D SMALLINT NULL,
    FACE_LP SMALLINT NULL,
    FACE_M SMALLINT NULL,
    FACE_OI SMALLINT NULL,
    FACE_V SMALLINT NULL,
    NUM_DENTE INTEGER NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_GUIA INTEGER NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_SEGURADO SMALLINT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SERIE_GUIA CHARACTER(1) NULL,
    TIPO_GUIA CHARACTER(1) NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_CALCULO DECIMAL(9, 2) NULL,
    VALOR_GLOSA DECIMAL(9, 2) NULL
);

CREATE TABLE GUIA_SERV_AUXILIAR (
    COD_BENEF VARCHAR(7) NULL,
    COD_CRED_REALIZ VARCHAR(8) NULL,
    COD_CRED_SOLIC VARCHAR(8) NULL,
    COD_ORGAO SMALLINT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NULL,
    CONTRASTE DECIMAL(11, 2) NULL,
    DATA_AUTORIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_REALIZACAO DATE NULL,
    DATA_SOLICITACAO DATE NULL,
    DATA1 DATE NULL,
    DATA2 DATE NULL,
    DATA3 DATE NULL,
    DATA4 DATE NULL,
    DATA5 DATE NULL,
    FUNC_AUTORIZ VARCHAR(15) NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_SEGURADO SMALLINT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SESSOES_AUTORIZ SMALLINT NULL,
    SESSOES_SOLIC SMALLINT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_CALCULO DECIMAL(11, 2) NULL,
    VALOR_GLOSA DECIMAL(11, 2) NULL
);

CREATE TABLE HIST_ACAO_JUD (
    DATA_CADASTRO DATE NULL,
    DATA_DEFESA DATE NOT NULL,
    FASE VARCHAR(50) NULL,
    HISTORICO VARCHAR(180) NULL,
    NUM_PROCESSO VARCHAR(11) NOT NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE HIST_CANCELA_RP (
    DATA DATE NULL,
    HORA TIME(3) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_TOTAL DECIMAL(11, 2) NULL
);

CREATE TABLE HIST_CAPA_ACRES_DESC (
    DATA_CADASTRO DATE NOT NULL,
    HORA_CADASTRO TIME(3) NOT NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    SEQUENCIA INTEGER NOT NULL,
    USUARIO VARCHAR(15) NOT NULL,
    VLR_ACRESCIMO DECIMAL(11, 2) NOT NULL,
    VLR_DESCONTO DECIMAL(11, 2) NOT NULL
);

CREATE TABLE HIST_PESSOAL (
    COD_HIST SMALLINT NOT NULL,
    COMPLEMENTO VARCHAR(180) NULL,
    DATA_DIARIO DATE NULL,
    DATA_FINAL DATE NULL,
    DATA_INICIAL DATE NULL,
    DESC_CONF VARCHAR(40) NULL,
    HISTORICO VARCHAR(180) NULL,
    NUM_DIARIO VARCHAR(6) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    SEQ_HIST INTEGER NOT NULL,
    VALIDO VARCHAR(180) NULL
);

CREATE TABLE HIST_TRANSF_MOVEL (
    COD_PATRIMONIO INTEGER NOT NULL,
    DATA_TRANSF DATE NULL,
    DESTINO_TRANF SMALLINT NULL,
    NOME_RESPONS VARCHAR(30) NULL,
    SITUACAO CHARACTER(1) NULL,
    USUARIO_TRANF VARCHAR(15) NULL
);

CREATE TABLE IMPOSTO_RENDA (
    ALIQUOTA1 DECIMAL(6, 2) NULL,
    ALIQUOTA2 DECIMAL(6, 2) NULL,
    ALIQUOTA3 DECIMAL(6, 2) NULL,
    ALIQUOTA4 DECIMAL(6, 2) NULL,
    ANO_MES CHARACTER(6) NOT NULL,
    DATA_CADASTRO DATE NULL,
    DEDUCAO_DEPEND DECIMAL(11, 2) NULL,
    DESCONTO1 DECIMAL(11, 2) NULL,
    DESCONTO2 DECIMAL(11, 2) NULL,
    DESCONTO3 DECIMAL(11, 2) NULL,
    DESCONTO4 DECIMAL(11, 2) NULL,
    FAIXA1 DECIMAL(11, 2) NULL,
    FAIXA2 DECIMAL(11, 2) NULL,
    FAIXA3 DECIMAL(11, 2) NULL,
    FAIXA4 DECIMAL(11, 2) NULL,
    IR_JURIDICA DECIMAL(6, 2) NULL,
    USUARIO_CADASTRO VARCHAR(15) NULL
);

CREATE TABLE INSPECAO (
    CID CHARACTER(8) NULL,
    COD_CREDENCIADO CHARACTER(8) NULL,
    DATA_FINAL DATE NULL,
    DATA_INCLUSAO DATE NULL,
    DATA_INICIAL DATE NULL,
    DATA_INSPECAO DATE NULL,
    DESCRICAO VARCHAR(200) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PRORROGA CHARACTER(1) NULL,
    QTDE_DIAS SMALLINT NULL,
    SEQUENCIA SMALLINT NOT NULL,
    TIPO_LICENCA SMALLINT NULL
);

CREATE TABLE LEIS (
    ARTIGO VARCHAR(10) NULL,
    ASSUNTO VARCHAR(30) NULL,
    COD_LEI SMALLINT NOT NULL,
    DATA_LEI DATE NULL,
    INCISO VARCHAR(10) NULL,
    NUMERO_LEI VARCHAR(10) NULL,
    TIPO_LEI VARCHAR(10) NULL
);

CREATE TABLE LIBERA_GUIA_ODONTO (
    DATA_LIBERACAO DATE NULL,
    LIBERADO_POR VARCHAR(15) NULL,
    NUM_DOC INTEGER NOT NULL,
    NUM_PROCESSO CHARACTER(10) NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL
);

CREATE TABLE LIXO_2 (
    DESCRICAO CHARACTER(50) NULL,
    MES INTEGER NULL,
    QUANTIDADE INTEGER NULL,
    VALOR DECIMAL(11, 2) NULL
);

CREATE TABLE LOCAL (
    ACESSO CHARACTER(1) NULL,
    COD_LOCAL SMALLINT NOT NULL,
    COD_LOCAL1 SMALLINT NULL,
    COD_LOCAL2 SMALLINT NULL,
    COD_REGIONAL SMALLINT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    LOTACAO_FOLHA VARCHAR(6) NULL,
    RESPONSAVEL VARCHAR(40) NULL,
    TETO_CH VARCHAR(4) NULL,
    TOTAL_DEPENDENTE INTEGER NULL,
    TOTAL_SEGURADO INTEGER NULL,
    UF CHARACTER(2) NULL
);

CREATE TABLE LOCAL_ATENDIMENTO (
    BAIRRO VARCHAR(35) NULL,
    CEP VARCHAR(10) NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    COD_LOCAL_ATEND INTEGER NOT NULL,
    COD_MUNICIPIO SMALLINT NULL,
    COD_TIPO_LOCAL SMALLINT NULL,
    ENDERECO VARCHAR(50) NULL,
    FAX VARCHAR(15) NULL,
    FONE VARCHAR(15) NULL,
    HOR_FIM_QUA TIME(3) NULL,
    HOR_FIM_QUI TIME(3) NULL,
    HOR_FIM_SAB TIME(3) NULL,
    HOR_FIM_SEG TIME(3) NULL,
    HOR_FIM_SEX TIME(3) NULL,
    HOR_FIM_TER TIME(3) NULL,
    HOR_INI_QUA TIME(3) NULL,
    HOR_INI_QUI TIME(3) NULL,
    HOR_INI_SAB TIME(3) NULL,
    HOR_INI_SEG TIME(3) NULL,
    HOR_INI_SEX TIME(3) NULL,
    HOR_INI_TER TIME(3) NULL,
    OBSERVACAO VARCHAR(150) NULL,
    QUARTA_ATENDE CHARACTER(1) NULL,
    QUINTA_ATENDE CHARACTER(1) NULL,
    SABADO_ATENDE CHARACTER(1) NULL,
    SALA_ATENDE CHARACTER(5) NULL,
    SEGUNDA_ATENDE CHARACTER(1) NULL,
    SEXTA_ATENDE CHARACTER(1) NULL,
    TERCA_ATENDE CHARACTER(1) NULL
);

CREATE TABLE LOCALIDADE (
    COD_LOCALIDADE INTEGER NULL,
    NOME_LOCALIDADE VARCHAR(40) NULL
);

CREATE TABLE LSTSEGURADOS (
    COD_BENEF VARCHAR(7) NULL,
    COD_ORGAO VARCHAR(2) NULL,
    NOME VARCHAR(50) NULL,
    NOME_MAE VARCHAR(40) NULL,
    NOME_PAI VARCHAR(40) NULL,
    NUM_SEGURADO SMALLINT NULL
);

CREATE TABLE MAT_MOVIMENTO (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_PRODUTO SMALLINT NOT NULL,
    DATA_MOVIMENTO DATE NOT NULL,
    NUM_NOTA VARCHAR(11) NULL,
    NUM_REQUISICAO VARCHAR(9) NULL,
    ORIGEM_DESTINO SMALLINT NULL,
    QTDE_ENTRADA DECIMAL(9, 3) NULL,
    QTDE_SAIDA DECIMAL(9, 3) NULL,
    TIPO_MOVIMENTO CHARACTER(1) NOT NULL,
    TOTAL DECIMAL(11, 2) NULL
);

CREATE TABLE MAT_PRODUTO (
    CLASSE SMALLINT NULL,
    COD_ELEN_CONT VARCHAR(9) NULL,
    COD_PRODUTO SMALLINT NOT NULL,
    DATA_INCLUSAO DATE NULL,
    DESCRICAO VARCHAR(40) NULL,
    DIZIMA_ANT DECIMAL(9, 2) NULL,
    DIZIMA_ATUAL DECIMAL(9, 2) NULL,
    DIZIMA_MES_ANT DECIMAL(9, 2) NULL,
    ESTOQ_ATUAL DECIMAL(9, 3) NULL,
    ESTOQ_MES_ANT DECIMAL(9, 3) NULL,
    PRECO DECIMAL(9, 2) NULL,
    PRECO_ANT DECIMAL(9, 2) NULL,
    PRECO_MES_ANT DECIMAL(9, 2) NULL,
    UNIDADE VARCHAR(10) NULL
);

CREATE TABLE MATRICULAS (
    MATRICULA CHARACTER(15) NULL,
    NOME CHARACTER(80) NULL
);

CREATE TABLE MOTORISTA (
    COD_MOTORISTA SMALLINT NOT NULL,
    ESCALA_VIAGEM CHARACTER(1) NULL,
    NOME VARCHAR(25) NOT NULL
);

CREATE TABLE MOV_CONTRIBUICAO (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_CARTORIO SMALLINT NULL,
    COD_MUNICIPIO SMALLINT NULL,
    COD_ORGAO SMALLINT NULL,
    DATA_PAGTO DATE NULL,
    DATA_VENCTO DATE NOT NULL,
    JUROS DECIMAL(6, 2) NULL,
    MULTA DECIMAL(10, 2) NULL,
    NUM_BOLETO VARCHAR(15) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    OBSERVACAO CHARACTER(40) NULL,
    OUTRAS_TAXAS DECIMAL(6, 2) NULL,
    SEQ_PAGAMENTO INTEGER NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    VALOR_PAGO DECIMAL(10, 2) NULL,
    VLR_SAUDE DECIMAL(10, 2) NULL
);

CREATE TABLE MOV_ODONTO (
    COD_BENEF VARCHAR(7) NOT NULL,
    COD_CREDENCIADO VARCHAR(8) NOT NULL,
    COD_PRI_ORGAO SMALLINT NOT NULL,
    COD_PROCEDIMENTO VARCHAR(8) NOT NULL,
    DATA_INCLUSAO DATE NULL,
    DATA_SERVICO DATE NOT NULL,
    FACE_D SMALLINT NULL,
    FACE_LP SMALLINT NULL,
    FACE_M SMALLINT NULL,
    FACE_OI SMALLINT NULL,
    FACE_V SMALLINT NULL,
    INCLUIDO_POR CHARACTER(15) NULL,
    NUM_DENTE SMALLINT NULL,
    NUM_GUIA INTEGER NULL,
    NUM_LANCTO INTEGER NOT NULL,
    NUM_PROCESSO VARCHAR(10) NULL,
    NUM_SEGURADO INTEGER NULL,
    NUM_SEQ_DEPEND SMALLINT NOT NULL,
    SERIE_GUIA CHARACTER(1) NULL,
    VIROU_GUIA CHARACTER(1) NOT NULL
);

CREATE TABLE MOV_PERITO (
    ANO_MES CHARACTER(6) NOT NULL,
    CH SMALLINT NOT NULL,
    COD_MUNICIPIO SMALLINT NOT NULL,
    COD_PERITO CHARACTER(8) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    FINANCEIRO CHARACTER(1) NOT NULL,
    SESSOES SMALLINT NOT NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE MOV_VEICULO (
    COD_SERVICO SMALLINT NULL,
    DATA_FIM DATE NULL,
    DATA_INICIO DATE NULL,
    DATA_LANCTO DATE NULL,
    DESTINO VARCHAR(15) NULL,
    KM_FIM VARCHAR(9) NULL,
    KM_INICIO VARCHAR(9) NULL,
    NUM_LANCAMENTO SMALLINT NOT NULL,
    OBS VARCHAR(60) NULL,
    ORIGEM VARCHAR(15) NULL,
    PLACA VARCHAR(7) NULL,
    QTD_UTILIZADA DECIMAL(4, 2) NULL,
    VALOR DECIMAL(8, 2) NULL
);

CREATE TABLE ORGAO_LOTACAO (
    COD_ORGAO_LOTACAO SMALLINT NOT NULL,
    DESC_ORGAO_LOTACAO VARCHAR(50) NOT NULL
);

CREATE TABLE PAG_PERITO (
    ALTERADO_POR VARCHAR(15) NULL,
    ANO_MES CHARACTER(6) NOT NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    COD_MUNICIPIO SMALLINT NOT NULL,
    DATA_ALTERACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_PAGTO DATE NULL,
    GERADO_POR VARCHAR(15) NULL,
    NUM_PROCESSO CHARACTER(10) NOT NULL,
    VALOR DECIMAL(11, 2) NULL
);

CREATE TABLE PARTE (
    COD_PARTE SMALLINT NOT NULL,
    COD_SISTEMA SMALLINT NULL,
    DESCRICAO VARCHAR(40) NULL,
    NOME_PARTE VARCHAR(40) NULL
);

CREATE TABLE PERCENT_CIRURGIA (
    COD_PERC_CIRURGIA SMALLINT NULL,
    DESC_PERC_CIRURGIA VARCHAR(30) NULL,
    PERC_CIRURGIA DECIMAL(5, 2) NULL
);

CREATE TABLE PERMISSAO (
    ALTERACAO CHARACTER(1) NOT NULL,
    COD_GRUPO SMALLINT NOT NULL,
    COD_PARTE SMALLINT NOT NULL,
    CONSULTA CHARACTER(1) NOT NULL,
    EXCLUSAO CHARACTER(1) NOT NULL,
    INCLUSAO CHARACTER(1) NOT NULL
);

CREATE TABLE PESSOAL (
    CARGO VARCHAR(6) NULL,
    COMP_ESCOLAR VARCHAR(60) NULL,
    DATA_ADMISSAO DATE NULL,
    DATA_EXONERACAO DATE NULL,
    DIA_BASE SMALLINT NULL,
    FOLHA_FREQ CHARACTER(1) NULL,
    FUNC_AUTORIZA SMALLINT NULL,
    FUNCAO VARCHAR(6) NULL,
    GRAU_ESCOLAR INTEGER NULL,
    LOTACAO SMALLINT NULL,
    LOTACAO_FOLHA VARCHAR(6) NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    NIVEL_ESCOLAR INTEGER NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    PRODUTIVIDADE CHARACTER(1) NULL,
    QTD_VALE SMALLINT NULL,
    QUADRO CHARACTER(1) NULL,
    REF_CARGO VARCHAR(6) NULL,
    STATUS_A CHARACTER(1) NULL
);

CREATE TABLE PLANO_BENEF (
    DATA_CADASTRO DATE NOT NULL,
    DATA_CONTRATO DATE NULL,
    NUM_CONTRATO INTEGER NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    SEQ_SEGURADO SMALLINT NOT NULL,
    SITUACAO SMALLINT NOT NULL,
    TABELA SMALLINT NOT NULL,
    TIPO_PLANO SMALLINT NOT NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE PLANO_FOLHA (
    ANO_MES VARCHAR(6) NOT NULL,
    DATA_REMESSA DATE NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    ORGAO_FOLHA VARCHAR(25) NOT NULL,
    RUBRICA SMALLINT NOT NULL,
    SEQ_SEGURADO SMALLINT NOT NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR DECIMAL(11, 2) NOT NULL
);

CREATE TABLE PLANO_TABELA (
    DATA_CADASTRO DATE NOT NULL,
    FAIXA CHARACTER(6) NULL,
    SITUACAO SMALLINT NOT NULL,
    TABELA SMALLINT NOT NULL,
    TIPO_PLANO SMALLINT NULL,
    USUARIO VARCHAR(15) NOT NULL,
    VALOR DECIMAL(13, 2) NOT NULL
);

CREATE TABLE PLANO_TIPO_TABELA (
    DATA_CADASTRO DATE NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    TABELA SMALLINT NOT NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE PORTE_ANESTESICO (
    CH SMALLINT NOT NULL,
    NUM_PORTE SMALLINT NOT NULL
);

CREATE TABLE PROCED_AUX_GIH (
    COD_CREDENCIADO CHARACTER(8) NULL,
    COD_PROCEDIMENTO CHARACTER(8) NOT NULL,
    DATA_REALIZACAO DATE NULL,
    NUM_DOC INTEGER NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    SESSOES_AUTOR SMALLINT NULL,
    SESSOES_SOLIC SMALLINT NULL,
    SITUACAO SMALLINT NOT NULL,
    VALOR_AUTOR DECIMAL(11, 2) NULL,
    VALOR_SOLIC DECIMAL(11, 2) NULL
);

CREATE TABLE PROCED_CIR_GIH (
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_PROCEDIMENTO VARCHAR(8) NOT NULL,
    DATA_REALIZACAO DATE NOT NULL,
    NUM_DOC INTEGER NOT NULL,
    PERCENTUAL_CIR SMALLINT NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    TIPO_PARTICIPACAO SMALLINT NOT NULL,
    VALOR_CALCULO DECIMAL(11, 2) NULL,
    VALOR_GLOSA DECIMAL(11, 2) NULL
);

CREATE TABLE PROCEDCIR1 (
    COD_CREDENCIADO VARCHAR(8) NULL,
    COD_PROCEDIMENTO VARCHAR(8) NOT NULL,
    DATA_REALIZACAO DATE NULL,
    NUM_DOC INTEGER NOT NULL,
    PERCENTUAL_CIR SMALLINT NOT NULL,
    SERIE_DOC CHARACTER(1) NOT NULL,
    TIPO_PARTICIPACAO SMALLINT NOT NULL,
    VALOR_CALCULO DECIMAL(11, 2) NULL,
    VALOR_GLOSA DECIMAL(11, 2) NULL
);

CREATE TABLE PRODUCAO_DIGITA (
    DATA_LANCAMENTO DATE NULL,
    QUANTIDADE INTEGER NULL,
    TIPO_GUIA VARCHAR(15) NULL,
    USUARIO VARCHAR(10) NULL
);

CREATE TABLE PRODUTIVIDADE (
    MES_ANO CHARACTER(6) NOT NULL,
    PROD_ADM SMALLINT NULL,
    PROD_ASSIST SMALLINT NULL,
    PROD_BENEF SMALLINT NULL
);

CREATE TABLE PRONT_CLINICO (
    ACOMP_CLINICO LONG VARCHAR(32700) NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    NUM_SEQ_DEPENDE SMALLINT NOT NULL
);

CREATE TABLE PRONTUARIO (
    ALTERACAO DATE NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    COD_TIPO_LOCAL SMALLINT NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    NUM_PLANILHA INTEGER NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    NUM_SEQ_DEPENDE SMALLINT NOT NULL,
    RELATO_CLINICO VARCHAR(500) NULL,
    SEQUENCIA SMALLINT NOT NULL,
    TRATAMENTO VARCHAR(250) NULL,
    USUARIO VARCHAR(10) NULL
);

CREATE TABLE QT_ATEND_MEDICO (
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    COD_TIPO_LOCAL SMALLINT NOT NULL,
    DATA DATE NULL,
    DATA_FINAL DATE NULL,
    DATA_INICIAL DATE NOT NULL,
    HORA TIME(3) NULL,
    QTD_PACIENTE SMALLINT NULL,
    USUARIO CHARACTER(8) NULL
);

CREATE TABLE RECIBO_MEDICO (
    COD_CREDENCIADO VARCHAR(8) NOT NULL,
    DATA_RECIBO DATE NOT NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    SEQ_RECIBO INTEGER NOT NULL
);

CREATE TABLE REFERENCIA (
    DESCRICAO VARCHAR(30) NULL,
    FATOR_INDICE DECIMAL(5, 2) NULL,
    REFERENCIA VARCHAR(6) NOT NULL,
    SAL_BASE DECIMAL(6, 2) NOT NULL
);

CREATE TABLE REGIONAL (
    COD_REGIONAL SMALLINT NOT NULL,
    DESC_REGIONAL VARCHAR(60) NULL
);

CREATE TABLE REPASSE (
    COD_REPASSE SMALLINT NULL,
    DATA_LANCAMENTO DATE NULL,
    HISTORICO VARCHAR(50) NULL,
    NUM_DOCUMENTO VARCHAR(15) NULL,
    NUM_LANCAMENTO INTEGER NOT NULL,
    VALOR_REPASSE DECIMAL(11, 2) NULL
);

CREATE TABLE RES_ASSMED (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    COD_LOCAL SMALLINT NOT NULL,
    ESPECIALIDADE VARCHAR(40) NOT NULL,
    QTDE_GLOSADA INTEGER NULL,
    QTDE_VALIDA INTEGER NULL,
    TIPO CHARACTER(10) NOT NULL,
    VLR_GLOSADO DECIMAL(11, 2) NULL,
    VLR_VALIDO DECIMAL(11, 2) NULL
);

CREATE TABLE RES_BENEF (
    DESC_LOCAL CHARACTER(30) NULL,
    DESC_ORGAO CHARACTER(30) NULL,
    QTDE INTEGER NULL,
    TIPO CHARACTER(1) NULL
);

CREATE TABLE RES_BENEF2 (
    COD_LOCAL SMALLINT NULL,
    COD_ORGAO SMALLINT NULL,
    FAIXA CHARACTER(10) NULL,
    QTDE INTEGER NULL,
    SEXO CHARACTER(1) NULL,
    TIPO_DEPENDE SMALLINT NULL
);

CREATE TABLE RES_BENEF3 (
    COD_ORGAO SMALLINT NULL,
    FAIXA CHARACTER(10) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    SEQ_SEGURADO SMALLINT NOT NULL,
    SEXO CHARACTER(1) NULL,
    TIPO_DEPENDE SMALLINT NULL,
    VALOR_ATEND DECIMAL(15, 2) NULL
);

CREATE TABLE RES_BENEF4 (
    ANO SMALLINT NOT NULL,
    DESCRICAO CHARACTER(30) NULL,
    FAIXA CHARACTER(10) NOT NULL,
    MES SMALLINT NOT NULL,
    QTDE INTEGER NOT NULL,
    VALOR DECIMAL(13, 2) NOT NULL
);

CREATE TABLE RES_BENEF5 (
    ANO INTEGER NULL,
    FAIXA VARCHAR(10) NULL,
    MES INTEGER NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_SEGURADO INTEGER NULL,
    VALOR DECIMAL(15, 2) NULL
);

CREATE TABLE RES_BENEF6 (
    FAIXA VARCHAR(10) NULL,
    NUM_SEGURADO INTEGER NULL,
    SEQ_SEGURADO INTEGER NULL,
    VALOR DECIMAL(15, 2) NULL
);

CREATE TABLE RES_FINANCEIRO (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_CATEGORIA INTEGER NOT NULL,
    COD_MUNICIPIO INTEGER NOT NULL,
    VALOR_DEBITO DECIMAL(11, 2) NOT NULL,
    VALOR_ESTIMADO CHARACTER(1) NOT NULL,
    VALOR_PAGO DECIMAL(11, 2) NOT NULL
);

CREATE TABLE RES_PROCANDA (
    ANO_MES CHARACTER(6) NOT NULL,
    COD_CATEGORIA SMALLINT NOT NULL,
    DESTINO SMALLINT NOT NULL,
    QTD_PROCS SMALLINT NULL,
    USUARIO VARCHAR(15) NOT NULL,
    VALOR_DEBITO DECIMAL(11, 2) NULL,
    VALOR_PAGO DECIMAL(11, 2) NULL
);

CREATE TABLE RESUMO_FALTAS (
    ANO CHARACTER(4) NOT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_RES INTEGER NOT NULL,
    DIAS_ANO DECIMAL(3) NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    OBS VARCHAR(20) NULL
);

CREATE TABLE RESUMOATEND (
    CANCELADA INTEGER NULL,
    DESC_TIPO_LOCAL VARCHAR(30) NOT NULL,
    FALTA INTEGER NULL,
    MARCADA INTEGER NULL,
    NOME_MEDICO VARCHAR(30) NOT NULL,
    RETORNO INTEGER NULL
);

CREATE TABLE RETENSAO_FOLHA (
    ALIQUOTA DECIMAL(4, 2) NULL,
    ANO_MES VARCHAR(6) NOT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    LANCAMENTO INTEGER NOT NULL,
    QTD_BEN SMALLINT NULL,
    TIPO SMALLINT NULL,
    VLR_FOLHA DECIMAL(11, 2) NULL,
    VLR_PATRONAL DECIMAL(11, 2) NULL,
    VLR_RECEITA DECIMAL(11, 2) NULL,
    VLR_REPASSE DECIMAL(11, 2) NULL
);

CREATE TABLE REVALIDACAO_CIS (
    DATA_REVALIDA DATE NOT NULL,
    HORA_REVALIDA TIME(3) NOT NULL,
    NOVA_DATA_CIS DATE NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    SEQ_SEGURADO INTEGER NOT NULL,
    ULTIMA_DATA_CIS DATE NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE REVALIDAR (
    COD_BENEF CHARACTER(7) NOT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    DATA_EMISSAO DATE NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_NOMEACAO DATE NULL,
    DATA_VALIDADE DATE NOT NULL,
    DEPENDENCIA CHARACTER(30) NULL,
    MUNICIPIO CHARACTER(30) NULL,
    NOME CHARACTER(40) NOT NULL,
    NUM_SEGURADO INTEGER NULL,
    NUM_SEQ_DEPEND SMALLINT NOT NULL,
    ORGAO CHARACTER(3) NULL,
    ORGAO_EXP_RG CHARACTER(3) NULL,
    RG CHARACTER(10) NULL,
    SEQUENCIA CHARACTER(2) NULL,
    SITUACAO VARCHAR(30) NULL,
    UF_EXP_RG CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL
);

CREATE TABLE SALARIO (
    MES_ANO CHARACTER(6) NOT NULL,
    VALOR DECIMAL(9, 2) NOT NULL
);

CREATE TABLE SEGURADO (
    BAIRRO VARCHAR(30) NULL,
    CEP CHARACTER(8) NULL,
    CLASSE VARCHAR(6) NULL,
    COD_BENEF CHARACTER(7) NOT NULL,
    COD_CARGO VARCHAR(6) NULL,
    COD_MUN_EMISSAO INTEGER NULL,
    COD_MUN_ENVIO INTEGER NULL,
    COD_MUNICIPIO SMALLINT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_SIT_ORGAO SMALLINT NULL,
    CPF VARCHAR(11) NULL,
    DATA_ATUALIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_EMISSAO_CART DATE NULL,
    DATA_NASCIMENTO DATE NULL,
    DATA_NOMEACAO DATE NULL,
    DATA_SITUACAO DATE NULL,
    DATA_VAL_CARTA DATE NULL,
    EMITE_CARTEIRA CHARACTER(1) NULL,
    EMITIR_OFICIO CHARACTER(1) NULL,
    ENDERECO_RESID VARCHAR(65) NULL,
    ESTADO_CIVIL CHARACTER(1) NULL,
    FAIXA_ETARIA CHARACTER(6) NULL,
    NOME VARCHAR(50) NOT NULL,
    NOME_MAE VARCHAR(45) NULL,
    NOME_PAI VARCHAR(45) NULL,
    NUM_FOLHA_ORGAO VARCHAR(7) NULL,
    NUM_OFICIO VARCHAR(8) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    ORGAO_EXP_RG CHARACTER(3) NULL,
    REFERENCIA VARCHAR(6) NULL,
    RG VARCHAR(15) NULL,
    SEQ_DEPEND SMALLINT NULL,
    SEXO CHARACTER(1) NULL,
    TELEFONE VARCHAR(15) NULL,
    TIPO_CARGO SMALLINT NULL,
    UF_EXP_RG CHARACTER(2) NULL,
    UF_ORIGEM CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_REMUNERACAO DECIMAL(9, 2) NULL
);

CREATE TABLE SEGURADO_AUXILIAR (
    BAIRRO VARCHAR(30) NULL,
    CEP CHARACTER(8) NULL,
    CLASSE VARCHAR(6) NULL,
    COD_BENEF CHARACTER(7) NOT NULL,
    COD_CARGO VARCHAR(6) NULL,
    COD_MUN_EMISSAO INTEGER NULL,
    COD_MUN_ENVIO INTEGER NULL,
    COD_MUNICIPIO SMALLINT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COD_SIT_ORGAO SMALLINT NULL,
    COD_SIT_SUB SMALLINT NULL,
    CPF VARCHAR(11) NULL,
    DATA_AFASTAMENTO DATE NULL,
    DATA_ATUALIZACAO DATE NULL,
    DATA_CADASTRO DATE NULL,
    DATA_EMISSAO_CART DATE NULL,
    DATA_INI_CARENCIA DATE NULL,
    DATA_NASCIMENTO DATE NULL,
    DATA_NOMEACAO DATE NULL,
    DATA_SITUACAO DATE NULL,
    DATA_VAL_CARTA DATE NULL,
    EMITE_CARTEIRA CHARACTER(1) NULL,
    EMITIR_OFICIO CHARACTER(1) NULL,
    ENDERECO_RESID VARCHAR(65) NULL,
    ENTREGA_MANUAL SMALLINT NULL,
    ESTADO_CIVIL CHARACTER(1) NULL,
    FAIXA_ETARIA CHARACTER(6) NULL,
    IDADE SMALLINT NULL,
    MOTIVO_BLOQUEIO VARCHAR(50) NULL,
    NOME VARCHAR(50) NOT NULL,
    NOME_MAE VARCHAR(45) NULL,
    NOME_PAI VARCHAR(45) NULL,
    NUM_FOLHA_ORGAO VARCHAR(7) NULL,
    NUM_OFICIO VARCHAR(8) NULL,
    NUM_SEGURADO INTEGER NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    ORGAO_EXP_RG CHARACTER(3) NULL,
    REFERENCIA VARCHAR(6) NULL,
    RG VARCHAR(15) NULL,
    SEQ_DEPEND SMALLINT NULL,
    SEXO CHARACTER(1) NULL,
    TELEFONE VARCHAR(15) NULL,
    TIPO_CARGO SMALLINT NULL,
    UF_EXP_RG CHARACTER(2) NULL,
    UF_ORIGEM CHARACTER(2) NULL,
    USUARIO VARCHAR(15) NULL,
    VALOR_REMUNERACAO DECIMAL(9, 2) NULL
);

CREATE TABLE SEGURADOS_FOLHA (
    BAIRRO VARCHAR(30) NULL,
    CEP VARCHAR(10) NULL,
    CIDADE VARCHAR(30) NULL,
    CPF VARCHAR(11) NULL,
    DATA_NASCIMENTO VARCHAR(8) NULL,
    ENDERECO VARCHAR(30) NULL,
    ESTADO VARCHAR(3) NULL,
    ESTADO_CIVIL VARCHAR(10) NULL,
    ESTADO_RG VARCHAR(3) NULL,
    IDENT_RG VARCHAR(15) NULL,
    MATRICULA VARCHAR(15) NULL,
    NOME VARCHAR(60) NULL,
    NOME_MAE VARCHAR(30) NULL,
    NOME_PAI VARCHAR(30) NULL,
    NUM_SEGURADO VARCHAR(12) NULL,
    SEXO VARCHAR(8) NULL,
    TELEFONE VARCHAR(12) NULL,
    UF_NASCIMENTO VARCHAR(3) NULL
);

CREATE TABLE SEGURADOS_FOLHA_PAGAMENTO (
    CD_SIT_FUN INTEGER NOT NULL
);

CREATE TABLE SISOBI_CARTORIO (
    BAIRRO VARCHAR(27) NULL,
    CEP VARCHAR(8) NULL,
    ENDERECO VARCHAR(55) NULL,
    GRSS1 VARCHAR(5) NOT NULL,
    GRSS2 VARCHAR(5) NOT NULL,
    MUNICIPIO VARCHAR(60) NULL,
    NOME VARCHAR(60) NULL,
    UF VARCHAR(2) NULL
);

CREATE TABLE SISTEMA (
    COD_SISTEMA SMALLINT NOT NULL,
    DESCRICAO VARCHAR(40) NOT NULL,
    EXECUTA_VER_ANT CHARACTER(1) NULL,
    VERSAO VARCHAR(10) NULL
);

CREATE TABLE SITUACAO_BENEF (
    COD_SIT_BENEF SMALLINT NOT NULL,
    DESC_SIT_BENEF VARCHAR(40) NULL
);

CREATE TABLE TABELA_IR (
    ALIQUOTA1 DECIMAL(5, 2) NULL,
    ALIQUOTA2 DECIMAL(5, 2) NULL,
    ALIQUOTA3 DECIMAL(5, 2) NULL,
    ALIQUOTA4 DECIMAL(5, 2) NULL,
    ANO_MES CHARACTER(6) NOT NULL,
    DATA_CADASTRO DATE NULL,
    DEDUCAO_DEPEND DECIMAL(9, 2) NULL,
    DESCONTO1 DECIMAL(9, 2) NULL,
    DESCONTO2 DECIMAL(9, 2) NULL,
    DESCONTO3 DECIMAL(9, 2) NULL,
    DESCONTO4 DECIMAL(9, 2) NULL,
    FAIXA1 DECIMAL(9, 2) NULL,
    FAIXA2 DECIMAL(9, 2) NULL,
    FAIXA3 DECIMAL(9, 2) NULL,
    FAIXA4 DECIMAL(9, 2) NULL,
    IR_JURIDICA DECIMAL(5, 2) NULL,
    USUARIO_CADASTRO CHARACTER(10) NULL
);

CREATE TABLE TEMP_DEBITO_EXOF (
    COD_BANCO VARCHAR(3) NULL,
    COD_CREDENCIADO CHARACTER(8) NOT NULL,
    ESPECIE CHARACTER(1) NOT NULL,
    NUM_PROCESSO VARCHAR(10) NULL,
    VALOR_EXOFICIO DECIMAL(11, 2) NULL
);

CREATE TABLE TEMP_PESSOALPROD (
    MATRICULA VARCHAR(7) NOT NULL,
    NDI DECIMAL(3, 2) NULL,
    NOME VARCHAR(40) NULL,
    VB_IF DECIMAL(8, 2) NULL
);

CREATE TABLE TEMPORARIA (
    AN_INICIAL_VERBA_REC_FUN INTEGER NULL,
    AN_ULT_CONTRIB_SIND_FUN INTEGER NULL,
    CD_BANCO_FGTS_FUN CHARACTER(10) NULL,
    CD_SIT_FUN INTEGER NULL
);

CREATE TABLE TESTE (
    MATRICULA VARCHAR(10) NULL
);

CREATE TABLE TESTEX1 (
    MATRICULA VARCHAR(10) NOT NULL,
    NOME VARCHAR(60) NULL,
    PERCENTUAL DECIMAL(5, 2) NULL
);

CREATE TABLE TETO_PERITO_JUNTA (
    ALTERADO_POR VARCHAR(15) NULL,
    CODIGO SMALLINT NOT NULL,
    DATA_ALTERACAO DATE NULL,
    QTD_CH_SERVICO SMALLINT NOT NULL,
    TETO INTEGER NOT NULL
);

CREATE TABLE TIPO_ACAO (
    COD_ACAO SMALLINT NOT NULL,
    DESC_ACAO VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_CARGO (
    COD_CARGO VARCHAR(6) NOT NULL,
    DESC_CARGO VARCHAR(30) NULL
);

CREATE TABLE TIPO_DEPENDENCIA (
    AGREGADO SMALLINT NULL,
    COD_TIPO_DEPEN SMALLINT NOT NULL,
    DESC_TIPO_DEPEN VARCHAR(30) NULL,
    LIMITE_IDADE SMALLINT NULL
);

CREATE TABLE TIPO_DOCUMENTO (
    COD_TIPO_DOC SMALLINT NOT NULL,
    DESC_TIPO_DOC VARCHAR(40) NULL
);

CREATE TABLE TIPO_HISTORICO (
    COD_HIST SMALLINT NOT NULL,
    DESC_HIST CHARACTER(30) NOT NULL
);

CREATE TABLE TIPO_LOCAL_ATENDE (
    COD_TIPO_LOCAL SMALLINT NOT NULL,
    DESC_TIPO_LOCAL VARCHAR(30) NOT NULL,
    QTDE_ATENDE SMALLINT NOT NULL
);

CREATE TABLE TIPO_OCORRENCIA (
    COD_OCORRE SMALLINT NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL
);

CREATE TABLE TIPO_REGIME (
    COD_REGIME SMALLINT NOT NULL,
    DESC_REGIME VARCHAR(30) NULL
);

CREATE TABLE TIPO_REPASSE (
    COD_REPASSE SMALLINT NOT NULL,
    DESC_REPASSE VARCHAR(40) NULL
);

CREATE TABLE TIPO_SERVICO (
    COD_SERVICO SMALLINT NOT NULL,
    DESC_SERVICO VARCHAR(25) NOT NULL
);

CREATE TABLE TRAMITE_PROCESSO (
    DATA_TRAMITE DATE NULL,
    DESTINO SMALLINT NOT NULL,
    ENCAMINHADO CHARACTER(1) NULL,
    HORA TIME(3) NULL,
    NUM_CAIXA_ARQ INTEGER NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    ORIGEM SMALLINT NOT NULL,
    RECEPTOR VARCHAR(20) NULL,
    STATUS_TRAMITE CHARACTER(1) NULL,
    USUARIO VARCHAR(20) NULL
);

CREATE TABLE TRAMITE2 (
    DATA_TRAMITE DATE NULL,
    DESTINO SMALLINT NOT NULL,
    ENCAMINHADO CHARACTER(1) NULL,
    HORA TIME(3) NULL,
    NUM_PROCESSO VARCHAR(10) NOT NULL,
    OBSERVACAO VARCHAR(50) NULL,
    ORIGEM SMALLINT NOT NULL,
    RECEPTOR VARCHAR(20) NULL,
    STATUS_TRAMITE CHARACTER(1) NULL,
    USUARIO VARCHAR(20) NULL
);

CREATE TABLE TROCA_MATRICULA (
    COD_BENEF VARCHAR(7) NOT NULL,
    COD_BENEF_NOVO VARCHAR(7) NOT NULL,
    COD_ORGAO INTEGER NOT NULL,
    COD_ORGAO_NOVO INTEGER NOT NULL,
    DATA_TROCA DATE NOT NULL,
    HORA_TROCA TIME(3) NOT NULL,
    USUARIO VARCHAR(15) NOT NULL
);

CREATE TABLE USUARIO (
    COD_GRUPO SMALLINT NOT NULL,
    DATA_INCLUSAO DATE NULL,
    NOME VARCHAR(40) NULL,
    NOME_ACESSO VARCHAR(15) NOT NULL
);

CREATE TABLE VALIDADE_DEPEND (
    COD_ORGAO SMALLINT NOT NULL,
    COD_SIT_ORGAO SMALLINT NOT NULL,
    COD_TIPO_DEPEND SMALLINT NOT NULL,
    LIMITE_VALIDADE DATE NULL,
    VALIDADE_FLAG SMALLINT NOT NULL,
    VALIDADE_MESES INTEGER NOT NULL
);

CREATE TABLE VALIDADE_SEGURADO (
    COD_ORGAO SMALLINT NOT NULL,
    COD_SIT_ORGAO SMALLINT NOT NULL,
    LIMITE_VALIDADE DATE NULL,
    VALIDADE_MESES INTEGER NOT NULL
);

CREATE TABLE VEICULO (
    BATERIA CHARACTER(1) NULL,
    BUZINA CHARACTER(1) NULL,
    CHAVE_RODA CHARACTER(1) NULL,
    COD_LOCAL SMALLINT NULL,
    COD_MOTORISTA SMALLINT NULL,
    COMBUSTIVEL VARCHAR(1) NULL,
    COR VARCHAR(10) NULL,
    DOCUMENTO VARCHAR(4) NULL,
    ESTEPE CHARACTER(1) NULL,
    EXTINTOR CHARACTER(1) NULL,
    FILTRO_AR CHARACTER(1) NULL,
    FILTRO_OLEO CHARACTER(1) NULL,
    LIMPADOR_PB CHARACTER(1) NULL,
    LUZES CHARACTER(1) NULL,
    MACACO CHARACTER(1) NULL,
    PLACA VARCHAR(7) NOT NULL,
    PNEUS CHARACTER(1) NULL,
    RADIADOR CHARACTER(1) NULL,
    RADIO CHARACTER(1) NULL,
    TIPO_VEICULO VARCHAR(10) NULL,
    TRIANGULO CHARACTER(1) NULL,
    TROCA_OLEO VARCHAR(9) NULL
);

CREATE TABLE VENCIMENTO (
    CLASSE VARCHAR(5) NOT NULL,
    COD_CARGO VARCHAR(6) NOT NULL,
    COD_ORGAO SMALLINT NOT NULL,
    COTAS DECIMAL(4) NULL,
    REFERENCIA VARCHAR(5) NOT NULL,
    VENCIMENTO DECIMAL(8, 2) NULL
);

CREATE TABLE XXTAB_REPLICA (
    DATA DATE NULL,
    NOME CHARACTER(10) NULL
);

